# Generated by Copilot under FIS AI Policy
# Rollback-CustomSecurity.ps1
# Restores SSRS configuration to Windows Authentication.

param(
    [string]$SSRSPath = 'C:\Program Files\Microsoft SQL Server Reporting Services',
    [string]$SqlServer = 'localhost',
    [switch]$Force,
    [switch]$DropDatabase
)

Set-StrictMode -Version Latest

# Requires Administrator privileges
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error 'This script must be run as Administrator.'
    exit 1
}

$ErrorActionPreference = 'Stop'

Write-Host '================================================' -ForegroundColor Red
Write-Host 'SSRS Custom Security Rollback' -ForegroundColor Red
Write-Host '================================================' -ForegroundColor Red

if (-not $Force) {
    $confirm = Read-Host 'Type YES to continue with rollback'
    if ($confirm -ne 'YES') {
        Write-Host 'Rollback cancelled.' -ForegroundColor Yellow
        exit 0
    }
} else {
    Write-Host 'Force flag set - skipping confirmation.' -ForegroundColor Yellow
}

Write-Host '[1/8] Stopping SSRS service' -ForegroundColor Yellow
$serviceName = 'SQLServerReportingServices'
$service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($service -and $service.Status -eq 'Running') {
    Stop-Service -Name $serviceName -Force
    Write-Host 'SSRS service stopped' -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Step 2: Restore config files from the most recent backup in .\backups\
# ---------------------------------------------------------------------------
Write-Host '[2/8] Restoring configuration files from backup' -ForegroundColor Yellow

$repoRoot   = Split-Path -Parent $PSScriptRoot
$backupsDir = Join-Path $repoRoot 'backups'

if (-not (Test-Path $backupsDir)) {
    Write-Error "Backups folder not found: $backupsDir — run Backup-Config.ps1 before deploying."
    exit 1
}

# Find most recent timestamped backup folder
$latestBackup = Get-ChildItem $backupsDir -Directory | Sort-Object Name -Descending | Select-Object -First 1
if ($null -eq $latestBackup) {
    Write-Error "No backup folders found in $backupsDir"
    exit 1
}

Write-Host "  Restoring from: $($latestBackup.FullName)" -ForegroundColor Gray

$restoreMap = @(
    @{ Src = "ReportServer\rsreportserver.config"; Dst = Join-Path $SSRSPath 'SSRS\ReportServer\rsreportserver.config' }
    @{ Src = "ReportServer\web.config";            Dst = Join-Path $SSRSPath 'SSRS\ReportServer\web.config' }
    @{ Src = "ReportServer\rssrvpolicy.config";    Dst = Join-Path $SSRSPath 'SSRS\ReportServer\rssrvpolicy.config' }
    @{ Src = "Portal\RSPortal.exe.config";         Dst = Join-Path $SSRSPath 'SSRS\Portal\RSPortal.exe.config' }
)

foreach ($entry in $restoreMap) {
    $src = Join-Path $latestBackup.FullName $entry.Src
    if (Test-Path $src) {
        Copy-Item $src -Destination $entry.Dst -Force
        Write-Host "  Restored: $($entry.Src)" -ForegroundColor Green
    } else {
        Write-Warning "Backup file not found, skipping: $src"
    }
}

Write-Host '[3/8] Removing CustomSecurity DLLs' -ForegroundColor Yellow
$dllName = 'BancPac.ReportingServices.BP360.dll'
$pdbName = 'BancPac.ReportingServices.BP360.pdb'
$dllsToRemove = @(
    Join-Path $SSRSPath "SSRS\ReportServer\bin\$dllName"
    Join-Path $SSRSPath "SSRS\ReportServer\bin\$pdbName"
    Join-Path $SSRSPath "SSRS\Portal\$dllName"
    Join-Path $SSRSPath "SSRS\Portal\$pdbName"
)
foreach ($dllPath in $dllsToRemove) {
    if (Test-Path $dllPath) {
        Remove-Item $dllPath -Force
        Write-Host "  Removed: $dllPath" -ForegroundColor Green
    }
}

Write-Host '[4/8] Removing Logon.aspx from ReportServer' -ForegroundColor Yellow
$logon = Join-Path $SSRSPath 'SSRS\ReportServer\Logon.aspx'
if (Test-Path $logon) {
    Remove-Item $logon -Force
    Write-Host "  Removed: $logon" -ForegroundColor Green
} else {
    Write-Host '  Logon.aspx not found — skipped' -ForegroundColor Gray
}

Write-Host '[5/8] Placeholder (IIS not used in SSRS 2019 Native Mode)' -ForegroundColor Gray

Write-Host '[6/8] Starting SSRS service' -ForegroundColor Yellow
if ($service) {
    Start-Service -Name $serviceName
    Write-Host 'SSRS service started' -ForegroundColor Green
}

Write-Host '[7/8] Validating SSRS endpoints' -ForegroundColor Yellow
Write-Host 'Waiting for SSRS to fully start...' -ForegroundColor Gray
Start-Sleep -Seconds 15

$testScript = Join-Path $PSScriptRoot 'Test-SSRSEndpoints.ps1'
if (Test-Path $testScript) {
    $testResult = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $testScript
    if ($LASTEXITCODE -eq 0) {
        Write-Host 'Endpoint validation: PASS' -ForegroundColor Green
    } else {
        Write-Warning 'Endpoint validation failed. Check output above for details.'
    }
} else {
    Write-Warning "Test script not found: $testScript - skipping validation"
}

# Step 8: Optional database cleanup
Write-Host '[8/8] UserAccounts database cleanup' -ForegroundColor Yellow

$shouldDropDatabase = $false

if ($DropDatabase) {
    $shouldDropDatabase = $true
    Write-Host 'DropDatabase flag set - will remove UserAccounts database' -ForegroundColor Yellow
} else {
    Write-Host 'The UserAccounts database contains custom security user accounts.' -ForegroundColor Gray
    Write-Host 'Keeping it allows faster re-deployment. Dropping it provides complete cleanup.' -ForegroundColor Gray
    $dropConfirm = Read-Host 'Drop UserAccounts database? (yes/no) [default: no]'
    if ($dropConfirm -eq 'yes') {
        $shouldDropDatabase = $true
    }
}

if ($shouldDropDatabase) {
    $restoreSqlPath = Join-Path (Split-Path -Parent $PSScriptRoot) 'Setup\RestoreDatabase.sql'
    if (Test-Path $restoreSqlPath) {
        try {
            Write-Host '  Dropping UserAccounts database...' -ForegroundColor Gray
            sqlcmd -S localhost -E -i "$restoreSqlPath" -b
            if ($LASTEXITCODE -eq 0) {
                Write-Host '  UserAccounts database dropped' -ForegroundColor Green
            } else {
                Write-Warning "sqlcmd returned exit code $LASTEXITCODE - database may not have been dropped"
            }
        } catch {
            Write-Warning "Failed to execute RestoreDatabase.sql: $_"
        }
    } else {
        Write-Warning "RestoreDatabase.sql not found at: $restoreSqlPath"
    }
} else {
    Write-Host '  UserAccounts database preserved (use -DropDatabase to remove)' -ForegroundColor Gray
}

Write-Host ''
Write-Host 'Rollback complete.' -ForegroundColor Green
Write-Host 'SSRS restored to Windows Authentication from definitive copy files.' -ForegroundColor White
