# Generated by Copilot under FIS AI Policy
# Setup-Users.ps1
# Registers users in the UserAccounts database for custom security authentication.

param(
    [string]$SqlServer   = '',    # auto-detected from Environment.ps1
    [string]$Database    = 'UserAccounts',
    [string]$UserName,
    [string]$Password,
    [string]$BankNumber  = '004', # bank prefix for UILogon.Key1 users (BNBR-UID format)
    [switch]$CreateTestUsers,
    [switch]$CreateBankTestUsers, # create bank-scoped users: BNBR-testuser, BNBR-admin, etc.
    [switch]$Integrated
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Auto-detect server environment ────────────────────────────────────────
. (Join-Path $PSScriptRoot 'Environment.ps1')
$_prof = Get-ServerProfile
if (-not $SqlServer) { $SqlServer = $_prof.SqlServer }

# ---------------------------------------------------------------------------
# Helper: Generate password hash + salt (matches AuthenticationUtilities.cs)
# ---------------------------------------------------------------------------
function New-PasswordHash {
    param(
        [string]$Password,
        [ref]$Salt
    )

    # Generate salt using RNGCryptoServiceProvider + Base64 (matches AuthenticationUtilities.CreateSalt)
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $saltBytes = New-Object byte[] 6   # 6 bytes = 8 Base64 chars, trimmed to 10 chars max
    $rng.GetBytes($saltBytes)
    $rng.Dispose()
    $saltString = [Convert]::ToBase64String($saltBytes)  # e.g. "abc+de=="
    $Salt.Value = $saltString

    # Combine password + salt and hash with SHA1 (matches AuthenticationUtilities.CreatePasswordHash)
    $combined = $Password + $saltString
    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    $hashBytes = $sha1.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($combined))
    $sha1.Dispose()

    # Convert to uppercase hex string (matches FormsAuthentication.HashPasswordForStoringInConfigFile output)
    $hashString = ($hashBytes | ForEach-Object { $_.ToString('X2') }) -join ''

    return $hashString
}

# ---------------------------------------------------------------------------
# Helper: Register a single user
# ---------------------------------------------------------------------------
function Register-User {
    param(
        [string]$SqlServer,
        [string]$Database,
        [string]$UserName,
        [string]$Password,
        [bool]$UseIntegratedAuth
    )
    
    if ([string]::IsNullOrWhiteSpace($UserName) -or [string]::IsNullOrWhiteSpace($Password)) {
        Write-Error "UserName and Password cannot be empty"
        return $false
    }
    
    $salt = $null
    $passwordHash = New-PasswordHash -Password $Password -Salt ([ref]$salt)
    
    Write-Host "  Registering user: $UserName" -ForegroundColor Gray
    
    # Use IF NOT EXISTS to handle duplicates gracefully (RegisterUser has no upsert logic)
    $query = @"
IF EXISTS (SELECT 1 FROM Users WHERE UserName = N'$UserName')
    PRINT 'User already exists: $UserName'
ELSE
    EXEC RegisterUser @userName = N'$UserName', @passwordHash = N'$passwordHash', @salt = N'$salt'
"@

    try {
        if ($UseIntegratedAuth) {
            $output = sqlcmd -S $SqlServer -d $Database -E -Q $query -b 2>&1
        } else {
            # SQL auth would require -U and -P parameters
            Write-Error "SQL authentication not yet implemented. Use -Integrated flag."
            return $false
        }

        if ($LASTEXITCODE -eq 0) {
            if ($output -match 'already exists') {
                Write-Host "  -- User already exists: $UserName (skipped)" -ForegroundColor Gray
            } else {
                Write-Host "  OK User registered: $UserName" -ForegroundColor Green
            }
            return $true
        } else {
            Write-Warning "Failed to register user: $UserName (sqlcmd exit code: $LASTEXITCODE)"
            if ($output) { Write-Warning "  Output: $output" }
            return $false
        }
    }
    catch {
        Write-Warning "Exception registering user ${UserName}: $_"
        return $false
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Custom Security - User Registration' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ''

# Check if database exists
$dbCheckQuery = "SELECT 1 FROM sys.databases WHERE name = '$Database'"
try {
    $dbExists = sqlcmd -S $SqlServer -E -Q $dbCheckQuery -h -1 -W 2>$null
    if (-not $dbExists -or ($dbExists -join '') -notmatch '1') {
        Write-Error "Database '$Database' not found on server '$SqlServer'. Run CreateUserStore.sql first."
        exit 1
    }
}
catch {
    Write-Error "Failed to connect to SQL Server: $_"
    exit 1
}

$successCount = 0
$failCount = 0

if ($CreateTestUsers) {
    Write-Host 'Creating default test users (direct login via logon.aspx)...' -ForegroundColor Yellow
    Write-Host ''

    $testUsers = @(
        @{ UserName = 'testuser';      Password = 'Test@123'   }
        @{ UserName = 'admin';         Password = 'Admin@123'  }
        @{ UserName = 'report_viewer'; Password = 'Viewer@123' }
    )

    foreach ($user in $testUsers) {
        if (Register-User -SqlServer $SqlServer -Database $Database `
                          -UserName $user.UserName -Password $user.Password `
                          -UseIntegratedAuth $Integrated) {
            $successCount++
        } else {
            $failCount++
        }
    }

    Write-Host ''
    Write-Host 'Test user credentials (logon.aspx):' -ForegroundColor Cyan
    foreach ($user in $testUsers) {
        Write-Host "  $($user.UserName) / $($user.Password)" -ForegroundColor Gray
    }
}

if ($CreateBankTestUsers) {
    Write-Host "Creating bank-scoped test users for bank $BankNumber (UILogon.Key1 flow)..." -ForegroundColor Yellow
    Write-Host ''

    # Bank-scoped username format: BNBR-UID (matches UILogon.Key1 path in UILogon.aspx)
    $bankTestUsers = @(
        @{ UserName = "$BankNumber-testuser";      Password = 'Test@123'   }
        @{ UserName = "$BankNumber-admin";         Password = 'Admin@123'  }
        @{ UserName = "$BankNumber-report_viewer"; Password = 'Viewer@123' }
    )

    foreach ($user in $bankTestUsers) {
        if (Register-User -SqlServer $SqlServer -Database $Database `
                          -UserName $user.UserName -Password $user.Password `
                          -UseIntegratedAuth $Integrated) {
            $successCount++
        } else {
            $failCount++
        }
    }

    Write-Host ''
    Write-Host "Bank-scoped test user credentials (UILogon.aspx with Key1, BNBR=$BankNumber):" -ForegroundColor Cyan
    foreach ($user in $bankTestUsers) {
        $uid = $user.UserName.Substring($BankNumber.Length + 1)
        Write-Host "  UID=$uid  PWD=$($user.Password)  BNBR=$BankNumber  (stored as: $($user.UserName))" -ForegroundColor Gray
    }
}
elseif ($UserName -and $Password) {
    Write-Host "Registering single user: $UserName" -ForegroundColor Yellow
    Write-Host ''
    
    if (Register-User -SqlServer $SqlServer -Database $Database `
                      -UserName $UserName -Password $Password `
                      -UseIntegratedAuth $Integrated) {
        $successCount++
    } else {
        $failCount++
    }
}
else {
    Write-Host 'Usage:' -ForegroundColor Cyan
    Write-Host '  .\Scripts\Setup-Users.ps1 -UserName "jdoe" -Password "Pass@123" -Integrated' -ForegroundColor White
    Write-Host '  .\Scripts\Setup-Users.ps1 -CreateTestUsers -Integrated' -ForegroundColor White
    Write-Host ''
    Write-Host 'Parameters:' -ForegroundColor Cyan
    Write-Host '  -UserName       Single user to register' -ForegroundColor White
    Write-Host '  -Password       Password for single user' -ForegroundColor White
    Write-Host '  -CreateTestUsers  Create default test accounts (testuser, admin, report_viewer)' -ForegroundColor White
    Write-Host '  -Integrated     Use Windows Authentication (required)' -ForegroundColor White
    Write-Host '  -SqlServer      SQL Server instance (default: localhost)' -ForegroundColor White
    Write-Host '  -Database       Database name (default: UserAccounts)' -ForegroundColor White
    Write-Host ''
    exit 0
}

Write-Host ''
Write-Host '================================================' -ForegroundColor Cyan
$resultColor = if ($failCount -eq 0) { 'Green' } else { 'Yellow' }
$exitCode = if ($failCount -eq 0) { 0 } else { 1 }
Write-Host "Registration complete: $successCount succeeded, $failCount failed" -ForegroundColor $resultColor
Write-Host '================================================' -ForegroundColor Cyan

exit $exitCode
