# Generated by Copilot under FIS AI Policy
# SmokeTest-Logon.ps1
param(
    [string]$Url   = '',   # auto-detected from Environment.ps1
    [string]$Label = 'Smoke test'
)
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot 'Environment.ps1')
$_prof = Get-ServerProfile
if (-not $Url) { $Url = $_prof.LogonUrl }

Write-Host "$Label -> $Url" -ForegroundColor Cyan
try {
    $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 20
    $code = [int]$response.StatusCode
    $looksLikeLogin = ($response.Content -match 'Logon|Login|User|Password')
    Write-Host "StatusCode      : $code" -ForegroundColor $(if ($code -eq 200) { 'Green' } else { 'Red' })
    Write-Host "LoginPageContent: $looksLikeLogin" -ForegroundColor $(if ($looksLikeLogin) { 'Green' } else { 'Yellow' })
    if ($code -eq 200) {
        Write-Host 'RESULT: PASS' -ForegroundColor Green
    } else {
        Write-Host 'RESULT: FAIL (unexpected status)' -ForegroundColor Red
        exit 1
    }
}
catch {
    $statusCode = $null
    # Safely check for Response property (absent in PowerShell 7+ HttpRequestException)
    $ex = $_.Exception
    if ($null -ne $ex -and $ex.PSObject.Properties.Match('Response').Count -gt 0) {
        $resp = $ex.Response
        if ($null -ne $resp -and $resp.PSObject.Properties.Match('StatusCode').Count -gt 0) {
            $statusCode = [int]$resp.StatusCode
        }
    }
    if ($null -ne $statusCode) { Write-Host "StatusCode: $statusCode" -ForegroundColor Red }
    Write-Host "Error     : $($_.Exception.Message)" -ForegroundColor Red
    Write-Host 'RESULT: FAIL' -ForegroundColor Red
    exit 1
}