# Generated by Copilot under FIS AI Policy
# Test-FormsAuth.ps1
# Comprehensive smoke test for SSRS Forms Authentication deployment.
# Tests login page, authentication, and SSRS endpoints.

param(
    [string]$LoginUrl = 'http://vmlenovo/ReportServer/logon.aspx',
    [string]$ReportServerUrl = 'http://vmlenovo/ReportServer',
    [string]$ReportsUrl = 'http://vmlenovo/Reports',
    [string]$TestUser = 'testuser',
    [string]$TestPassword = 'Test@123',
    [switch]$SkipAuthTest,
    [switch]$Verbose
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Forms Authentication Smoke Test' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ''

$allPassed = $true

# ---------------------------------------------------------------------------
# Test 1: Login page accessibility
# ---------------------------------------------------------------------------
Write-Host '[1/4] Testing login page accessibility' -ForegroundColor Yellow
Write-Host "  URL: $LoginUrl" -ForegroundColor Gray

try {
    $response = Invoke-WebRequest -Uri $LoginUrl -UseBasicParsing -ErrorAction Stop
    $statusCode = [int]$response.StatusCode
    
    if ($statusCode -eq 200 -and $response.Content -match 'Logon') {
        Write-Host "  Status: $statusCode OK" -ForegroundColor Green
        Write-Host "  Result: PASS - Login page is accessible" -ForegroundColor Green
    }
    else {
        Write-Host "  Status: $statusCode" -ForegroundColor Red
        Write-Host "  Result: FAIL - Unexpected response" -ForegroundColor Red
        $allPassed = $false
    }
}
catch {
    Write-Host "  Status: Error" -ForegroundColor Red
    Write-Host "  Result: FAIL - $_" -ForegroundColor Red
    $allPassed = $false
}
Write-Host ''

# ---------------------------------------------------------------------------
# Test 2: ReportServer redirects to login (unauthenticated)
# ---------------------------------------------------------------------------
Write-Host '[2/4] Testing ReportServer redirect behavior' -ForegroundColor Yellow
Write-Host "  URL: $ReportServerUrl" -ForegroundColor Gray

try {
    $response = Invoke-WebRequest -Uri $ReportServerUrl -UseBasicParsing -MaximumRedirection 0 -ErrorAction SilentlyContinue
    $statusCode = [int]$response.StatusCode
    
    # Should not get here (no redirect = success with 200)
    Write-Host "  Status: $statusCode" -ForegroundColor Yellow
    Write-Host "  Result: WARNING - No redirect (anonymous access enabled?)" -ForegroundColor Yellow
}
catch {
    if ($_.Exception.Response) {
        $statusCode = [int]$_.Exception.Response.StatusCode
        $location = $null
        try {
            $location = $_.Exception.Response.Headers.Location
        } catch {}
        
        if ($statusCode -eq 302) {
            Write-Host "  Status: 302 Redirect" -ForegroundColor Green
            if ($location) {
                Write-Host "  Location: $location" -ForegroundColor Gray
            }
            Write-Host "  Result: PASS - Redirects to login page" -ForegroundColor Green
        }
        elseif ($statusCode -eq 401) {
            Write-Host "  Status: 401 Unauthorized" -ForegroundColor Yellow
            Write-Host "  Result: WARNING - Windows Auth might still be active" -ForegroundColor Yellow
        }
        else {
            Write-Host "  Status: $statusCode" -ForegroundColor Red
            Write-Host "  Result: FAIL - Unexpected status" -ForegroundColor Red
            $allPassed = $false
        }
    }
    else {
        Write-Host "  Result: FAIL - $_" -ForegroundColor Red
        $allPassed = $false
    }
}
Write-Host ''

# ---------------------------------------------------------------------------
# Test 3: Reports portal redirects to login (unauthenticated)
# ---------------------------------------------------------------------------
Write-Host '[3/4] Testing Reports portal redirect behavior' -ForegroundColor Yellow
Write-Host "  URL: $ReportsUrl" -ForegroundColor Gray

try {
    $response = Invoke-WebRequest -Uri $ReportsUrl -UseBasicParsing -MaximumRedirection 0 -ErrorAction SilentlyContinue
    $statusCode = [int]$response.StatusCode
    
    Write-Host "  Status: $statusCode" -ForegroundColor Yellow
    Write-Host "  Result: WARNING - No redirect" -ForegroundColor Yellow
}
catch {
    if ($_.Exception.Response) {
        $statusCode = [int]$_.Exception.Response.StatusCode
        
        if ($statusCode -eq 302) {
            Write-Host "  Status: 302 Redirect" -ForegroundColor Green
            Write-Host "  Result: PASS - Redirects to login page" -ForegroundColor Green
        }
        elseif ($statusCode -eq 401) {
            Write-Host "  Status: 401 Unauthorized" -ForegroundColor Yellow
            Write-Host "  Result: WARNING - Windows Auth might still be active" -ForegroundColor Yellow
        }
        else {
            Write-Host "  Status: $statusCode" -ForegroundColor Red
            Write-Host "  Result: FAIL - Unexpected status" -ForegroundColor Red
            $allPassed = $false
        }
    }
    else {
        Write-Host "  Result: FAIL - $_" -ForegroundColor Red
        $allPassed = $false
    }
}
Write-Host ''

# ---------------------------------------------------------------------------
# Test 4: Login functionality (optional)
# ---------------------------------------------------------------------------
if (-not $SkipAuthTest) {
    Write-Host '[4/4] Testing login functionality' -ForegroundColor Yellow
    Write-Host "  User: $TestUser" -ForegroundColor Gray
    
    try {
        # Create session to maintain cookies
        $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
        
        # GET login page first to obtain ViewState tokens
        $getResponse = Invoke-WebRequest -Uri $LoginUrl -WebSession $session -UseBasicParsing
        $viewState          = if ($getResponse.Content -match 'name="__VIEWSTATE".*?value="([^"]*)"')          { $matches[1] } else { '' }
        $viewStateGenerator = if ($getResponse.Content -match 'name="__VIEWSTATEGENERATOR".*?value="([^"]*)"') { $matches[1] } else { '' }
        $eventValidation    = if ($getResponse.Content -match 'name="__EVENTVALIDATION".*?value="([^"]*)"')    { $matches[1] } else { '' }

        $loginBody = @{
            '__VIEWSTATE'          = $viewState
            '__VIEWSTATEGENERATOR' = $viewStateGenerator
            '__EVENTVALIDATION'    = $eventValidation
            'TxtUser'              = $TestUser
            'TxtPwd'               = $TestPassword
            'BtnLogon'             = 'Logon'
        }

        $loginResponse = Invoke-WebRequest -Uri $LoginUrl -Method POST -Body $loginBody -WebSession $session -UseBasicParsing -MaximumRedirection 0 -ErrorAction SilentlyContinue

        # Check for authentication cookie
        $authCookie = $session.Cookies.GetCookies($LoginUrl) | Where-Object { $_.Name -match 'sqlAuthCookie|AuthCookie|FormsAuth|\.ASPXAUTH' }
        
        if ($authCookie) {
            Write-Host "  Authentication cookie found: $($authCookie.Name)" -ForegroundColor Green
            Write-Host "  Result: PASS - Login successful" -ForegroundColor Green
        }
        else {
            Write-Host "  Result: PARTIAL - Response received but no auth cookie found" -ForegroundColor Yellow
        }
    }
    catch {
        if ($_.Exception.Response) {
            $statusCode = [int]$_.Exception.Response.StatusCode
            
            if ($statusCode -eq 302) {
                # Redirect after login is often success
                Write-Host "  Status: 302 Redirect (likely success)" -ForegroundColor Green
                Write-Host "  Result: PASS - Login appears successful" -ForegroundColor Green
            }
            else {
                Write-Host "  Status: $statusCode" -ForegroundColor Yellow
                Write-Host "  Result: WARNING - Unexpected response" -ForegroundColor Yellow
            }
        }
        else {
            Write-Host "  Result: FAIL - $_" -ForegroundColor Red
            $allPassed = $false
        }
    }
    Write-Host ''
}
else {
    Write-Host '[4/4] Login functionality test skipped (-SkipAuthTest)' -ForegroundColor Gray
    Write-Host ''
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Summary' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan

# Check SSRS Service
Write-Host "SSRS Service:" -NoNewline
$service = Get-Service -Name SQLServerReportingServices -ErrorAction SilentlyContinue
if ($service) {
    $color = if ($service.Status -eq 'Running') { 'Green' } else { 'Red' }
    Write-Host " $($service.Status)" -ForegroundColor $color
}
else {
    Write-Host " Not Found" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ''
if ($allPassed) {
    Write-Host 'Overall Result: PASS - Forms Authentication is working correctly' -ForegroundColor Green
    exit 0
}
else {
    Write-Host 'Overall Result: FAIL - One or more tests failed' -ForegroundColor Red
    exit 1
}
