# Generated by Copilot under FIS AI Policy
# Test-Login.ps1
# Tests actual login functionality with test users

param(
    [string]$LoginUrl        = '',   # auto-detected from Environment.ps1
    [string]$ReportServerUrl = '',   # auto-detected from Environment.ps1
    [switch]$Verbose
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'Environment.ps1')
$_prof = Get-ServerProfile
if (-not $LoginUrl)        { $LoginUrl        = $_prof.LogonUrl }
if (-not $ReportServerUrl) { $ReportServerUrl = $_prof.ReportServerUrl }

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Login Functionality Test' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ''

# Test credentials
$testUsers = @(
    @{ UserName = 'testuser'; Password = 'Test@123' }
    @{ UserName = 'admin'; Password = 'Admin@123' }
    @{ UserName = 'report_viewer'; Password = 'Viewer@123' }
)

$passCount = 0
$failCount = 0

foreach ($user in $testUsers) {
    Write-Host "Testing login: $($user.UserName)" -ForegroundColor Yellow
    Write-Host "  URL: $LoginUrl" -ForegroundColor Gray
    
    try {
        # Create a new session for each test to get fresh cookies
        $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
        
        # First, GET the login page to get ViewState
        $getResponse = Invoke-WebRequest -Uri $LoginUrl -WebSession $session -UseBasicParsing
        
        # Extract ViewState fields
        $viewState = ''
        $viewStateGenerator = ''
        $eventValidation = ''
        
        if ($getResponse.Content -match 'name="__VIEWSTATE".*?value="([^"]*)"') {
            $viewState = $matches[1]
        }
        if ($getResponse.Content -match 'name="__VIEWSTATEGENERATOR".*?value="([^"]*)"') {
            $viewStateGenerator = $matches[1]
        }
        if ($getResponse.Content -match 'name="__EVENTVALIDATION".*?value="([^"]*)"') {
            $eventValidation = $matches[1]
        }
        
        # Prepare login form data with correct field names
        $body = @{
            '__VIEWSTATE' = $viewState
            '__VIEWSTATEGENERATOR' = $viewStateGenerator
            '__EVENTVALIDATION' = $eventValidation
            'TxtUser' = $user.UserName
            'TxtPwd' = $user.Password
            'BtnLogon' = 'Logon'
        }
        
        # Attempt login
        $response = $null
        try {
            $response = Invoke-WebRequest -Uri $LoginUrl -Method POST -Body $body -WebSession $session -UseBasicParsing -MaximumRedirection 5 -ErrorAction Stop
        }
        catch {
            # Handle 401 during POST - may be normal for some IIS configurations
            if ($_.Exception.Response -and [int]$_.Exception.Response.StatusCode -eq 401) {
                Write-Host "  Status: 401 on POST (checking if this is authentication flow...)" -ForegroundColor Yellow
                # Try to get the response content anyway
                try {
                    $stream = $_.Exception.Response.GetResponseStream()
                    $reader = New-Object System.IO.StreamReader($stream)
                    $responseContent = $reader.ReadToEnd()
                    $reader.Close()
                    $stream.Close()
                    
                    if ($responseContent -match 'Invalid|incorrect|failed|error') {
                        Write-Host "  Status:Login rejected" -ForegroundColor Red
                        Write-Host "  Result: FAIL - Invalid credentials in response" -ForegroundColor Red
                        $failCount++
                        continue
                    }
                }
                catch {}
            }
            throw
        }
        
        # Check for authentication cookie
        $allCookies = $session.Cookies.GetCookies($LoginUrl)
        $authCookie = $allCookies | Where-Object {
            $_.Name -match 'sqlAuthCookie|AuthCookie|FormsAuth|\.ASPXAUTH'
        }
        
        if ($authCookie) {
            Write-Host "  Status: Login successful" -ForegroundColor Green
            Write-Host "  Cookie: $($authCookie.Name)" -ForegroundColor Gray
            
            # Try accessing ReportServer with authenticated session
            try {
                $rsResponse = Invoke-WebRequest -Uri $ReportServerUrl -WebSession $session -UseBasicParsing -MaximumRedirection 0 -ErrorAction SilentlyContinue
                $rsStatus = [int]$rsResponse.StatusCode
                
                if ($rsStatus -eq 200) {
                    Write-Host "  ReportServer Access: Authenticated (200 OK)" -ForegroundColor Green
                    Write-Host "  Result: PASS - Full authentication working" -ForegroundColor Green
                    $passCount++
                }
                else {
                    Write-Host "  ReportServer Access: Status $rsStatus" -ForegroundColor Yellow
                    Write-Host "  Result: PARTIAL - Login works but ReportServer access unclear" -ForegroundColor Yellow
                    $passCount++
                }
            }
            catch {
                if ($_.Exception.Response) {
                    $rsStatus = [int]$_.Exception.Response.StatusCode
                    if ($rsStatus -eq 302) {
                        Write-Host "  ReportServer Access: Still redirecting (302)" -ForegroundColor Yellow
                        Write-Host "  Result: PARTIAL - Cookie exists but may not be working" -ForegroundColor Yellow
                    }
                    else {
                        Write-Host "  ReportServer Access: Status $rsStatus" -ForegroundColor Yellow
                        Write-Host "  Result: PARTIAL - Login succeeded, ReportServer status $rsStatus" -ForegroundColor Yellow
                    }
                }
                else {
                    Write-Host "  ReportServer Access: Error - $($_.Exception.Message)" -ForegroundColor Yellow
                }
                $passCount++
            }
        }
        else {
            # Check response for error messages
            if ($response.Content -match 'Invalid|incorrect|failed|error') {
                Write-Host "  Status: Login failed - Invalid credentials" -ForegroundColor Red
                Write-Host "  Result: FAIL - Authentication rejected" -ForegroundColor Red
                $failCount++
            }
            elseif ($response.StatusCode -eq 200 -and $response.Content.Length -gt 0) {
                Write-Host "  Status: Response received but no auth cookie" -ForegroundColor Yellow
                Write-Host "  Result: PARTIAL - May need to check cookie configuration" -ForegroundColor Yellow
                $passCount++
            }
            else {
                Write-Host "  Status: Unexpected response" -ForegroundColor Red
                Write-Host "  Result: FAIL - No authentication cookie found" -ForegroundColor Red
                $failCount++
            }
        }
        
        if ($Verbose -and $allCookies) {
            Write-Host "  All Cookies:" -ForegroundColor Gray
            $allCookies | ForEach-Object {
                Write-Host "    $($_.Name) = $($_.Value.Substring(0, [Math]::Min(20, $_.Value.Length)))..." -ForegroundColor DarkGray
            }
        }
    }
    catch {
        Write-Host "  Status: Error" -ForegroundColor Red
        Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "  Result: FAIL - Request failed" -ForegroundColor Red
        $failCount++
    }
    
    Write-Host ''
}

# Test invalid credentials
Write-Host "Testing invalid credentials (should fail)" -ForegroundColor Yellow
Write-Host "  User: baduser / wrongpassword" -ForegroundColor Gray

try {
    $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
    
    # GET the login page to get ViewState
    $getResponse = Invoke-WebRequest -Uri $LoginUrl -WebSession $session -UseBasicParsing
    
    # Extract ViewState fields
    $viewState = ''
    $viewStateGenerator = ''
    $eventValidation = ''
    
    if ($getResponse.Content -match 'name="__VIEWSTATE".*?value="([^"]*)"') {
        $viewState = $matches[1]
    }
    if ($getResponse.Content -match 'name="__VIEWSTATEGENERATOR".*?value="([^"]*)"') {
        $viewStateGenerator = $matches[1]
    }
    if ($getResponse.Content -match 'name="__EVENTVALIDATION".*?value="([^"]*)"') {
        $eventValidation = $matches[1]
    }
    
    $body = @{
        '__VIEWSTATE' = $viewState
        '__VIEWSTATEGENERATOR' = $viewStateGenerator
        '__EVENTVALIDATION' = $eventValidation
        'TxtUser' = 'baduser'
        'TxtPwd' = 'wrongpassword'
        'BtnLogon' = 'Logon'
    }
    
    $response = Invoke-WebRequest -Uri $LoginUrl -Method POST -Body $body -WebSession $session -UseBasicParsing -ErrorAction Stop
    
    # Check if we got an error message in the response
    if ($response.Content -match 'Invalid|incorrect|failed|error|denied') {
        Write-Host "  Status: Login correctly rejected" -ForegroundColor Green
        Write-Host "  Result: PASS - Invalid credentials properly handled" -ForegroundColor Green
    }
    else {
        # Check for auth cookie (shouldn't exist)
        $authCookie = $session.Cookies.GetCookies($LoginUrl) | Where-Object { 
            $_.Name -match 'AuthCookie|FormsAuth|\.ASPXAUTH' 
        }
        
        $authCookie = $session.Cookies.GetCookies($LoginUrl) | Where-Object {
            $_.Name -match 'sqlAuthCookie|AuthCookie|FormsAuth|\.ASPXAUTH'
        }
        if ($authCookie) {
            Write-Host "  Status: WARNING - Invalid login succeeded!" -ForegroundColor Red
            Write-Host "  Result: FAIL - Security issue: bad credentials accepted" -ForegroundColor Red
            $failCount++
        }
        else {
            Write-Host "  Status: No auth cookie (as expected)" -ForegroundColor Green
            Write-Host "  Result: PASS - Invalid credentials rejected" -ForegroundColor Green
        }
    }
}
catch {
    Write-Host "  Status: Request error (may be normal for invalid creds)" -ForegroundColor Gray
    Write-Host "  Result: PASS - Invalid credentials rejected" -ForegroundColor Green
}

Write-Host ''

# Summary
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Summary' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host "Valid Users Tested: $($testUsers.Count)" -ForegroundColor White
Write-Host "Successful Logins:  $passCount" -ForegroundColor $(if ($passCount -eq $testUsers.Count) { 'Green' } else { 'Yellow' })
Write-Host "Failed Logins:      $failCount" -ForegroundColor $(if ($failCount -eq 0) { 'Green' } else { 'Red' })
Write-Host ''

if ($failCount -eq 0 -and $passCount -eq $testUsers.Count) {
    Write-Host 'Overall Result: PASS - All login tests successful' -ForegroundColor Green
    exit 0
}
elseif ($passCount -gt 0 -and $failCount -eq 0) {
    Write-Host 'Overall Result: PARTIAL - Some logins working, check warnings' -ForegroundColor Yellow
    exit 0
}
else {
    Write-Host 'Overall Result: FAIL - One or more login tests failed' -ForegroundColor Red
    exit 1
}
