# Generated by Copilot under FIS AI Policy
# Test-SSRSEndpoints.ps1
# Verifies that SSRS ReportServer and Reports endpoints are responding correctly.
# Used to validate successful rollback to Windows Authentication or deployment status.

param(
    [string]$ServerUrl = '',   # auto-detected from Environment.ps1
    [switch]$Verbose
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'Environment.ps1')
$_prof = Get-ServerProfile
if (-not $ServerUrl) {
    # Derive base URL from ReportServerUrl (strip /ReportServer suffix)
    $ServerUrl = $_prof.ReportServerUrl -replace '/ReportServer$', ''
}

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Endpoints Test' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ''

$reportServerUrl = "$ServerUrl/ReportServer"
$reportsUrl = "$ServerUrl/Reports"

$results = @()

# Test function
function Test-Endpoint {
    param(
        [string]$Url,
        [string]$Name
    )
    
    Write-Host "Testing: $Name" -ForegroundColor Yellow
    Write-Host "  URL: $Url" -ForegroundColor Gray
    
    try {
        $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -MaximumRedirection 0 -ErrorAction SilentlyContinue
        $statusCode = [int]$response.StatusCode
        $statusText = try { $response.StatusDescription } catch { "OK" }
    }
    catch {
        if ($_.Exception.Response) {
            $statusCode = [int]$_.Exception.Response.StatusCode
            $statusText = "Error"
            try { $statusText = $_.Exception.Response.StatusDescription } catch {}
            try { if (-not $statusText -or $statusText -eq "Error") { $statusText = $_.Exception.Response.ReasonPhrase } } catch {}
        }
        else {
            $statusCode = 0
            $statusText = $_.Exception.Message
        }
    }
    
    # Determine result
    $isSuccess = $false
    $message = ""
    
    switch ($statusCode) {
        200 {
            $isSuccess = $true
            $message = "OK - Endpoint accessible (likely anonymous or authenticated)"
        }
        302 {
            $isSuccess = $true
            $message = "Redirect - Forms authentication redirecting to login (expected for custom auth)"
        }
        401 {
            $isSuccess = $true
            $message = "Unauthorized - Windows Authentication active (expected after rollback)"
        }
        403 {
            $isSuccess = $false
            $message = "Forbidden - Access denied (check permissions)"
        }
        404 {
            $isSuccess = $false
            $message = "Not Found - Endpoint missing or SSRS not configured"
        }
        500 {
            $isSuccess = $false
            $message = "Internal Server Error - SSRS configuration problem"
        }
        503 {
            $isSuccess = $false
            $message = "Service Unavailable - SSRS service not running or starting"
        }
        0 {
            $isSuccess = $false
            $message = "Connection Failed - $statusText"
        }
        default {
            $isSuccess = $false
            $message = "Unexpected status"
        }
    }
    
    # Display result
    if ($isSuccess) {
        Write-Host "  Status: $statusCode - $statusText" -ForegroundColor Green
        Write-Host "  Result: PASS - $message" -ForegroundColor Green
    }
    else {
        Write-Host "  Status: $statusCode - $statusText" -ForegroundColor Red
        Write-Host "  Result: FAIL - $message" -ForegroundColor Red
    }
    
    if ($Verbose -and $response) {
        Write-Host "  Headers:" -ForegroundColor Gray
        $response.Headers.GetEnumerator() | ForEach-Object {
            Write-Host "    $($_.Key): $($_.Value)" -ForegroundColor DarkGray
        }
    }
    
    Write-Host ''
    
    return [PSCustomObject]@{
        Name = $Name
        Url = $Url
        StatusCode = $statusCode
        StatusText = $statusText
        IsSuccess = $isSuccess
        Message = $message
    }
}

# Test ReportServer
$results += Test-Endpoint -Url $reportServerUrl -Name "ReportServer Web Service"

# Test Reports Portal
$results += Test-Endpoint -Url $reportsUrl -Name "Reports Portal"

# Summary
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Summary' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan

$passCount = @($results | Where-Object { $_.IsSuccess }).Count
$failCount = @($results | Where-Object { -not $_.IsSuccess }).Count

foreach ($result in $results) {
    $color = if ($result.IsSuccess) { 'Green' } else { 'Red' }
    $status = if ($result.IsSuccess) { 'PASS' } else { 'FAIL' }
    Write-Host "$status - $($result.Name) [$($result.StatusCode)]" -ForegroundColor $color
}

Write-Host ''
Write-Host "Total: $($results.Count) | Pass: $passCount | Fail: $failCount" -ForegroundColor $(if ($failCount -eq 0) { 'Green' } else { 'Yellow' })
Write-Host ''

# Check SSRS Service
Write-Host "SSRS Service Status:" -ForegroundColor Cyan
$service = Get-Service -Name SQLServerReportingServices -ErrorAction SilentlyContinue
if ($service) {
    $color = if ($service.Status -eq 'Running') { 'Green' } else { 'Yellow' }
    Write-Host "  $($service.DisplayName): $($service.Status)" -ForegroundColor $color
}
else {
    Write-Host "  SQLServerReportingServices: Not Found" -ForegroundColor Red
}

Write-Host '================================================' -ForegroundColor Cyan

# Exit code
if ($failCount -eq 0) {
    exit 0
}
else {
    exit 1
}
