# Generated by Copilot under FIS AI Policy
# Test-UILogon.ps1
# Tests the UILogon.aspx endpoint using curl.exe.
# Posts UID/PWD/BNBR/KEY and checks whether sqlAuthCookie is returned.
#
# USAGE:
#   .\Test-UILogon.ps1 -UID testuser -PWD Test@123 -BNBR 004
#   .\Test-UILogon.ps1 -UID jdoe -PWD Secret@1 -BNBR 004 -UseKey2
#   .\Test-UILogon.ps1 -UID testuser -PWD Test@123 -BNBR 004 -BaseUrl http://vmlenovo

param(
    [string]$BaseUrl    = '',        # auto-detected from Environment.ps1 (ReportServer URL)
    [string]$LogonPath  = '/logon.aspx',     # logon.aspx is the loginUrl so always accessible; UILogon API is embedded in it
    [string]$UID,
    [string]$PWD,
    [string]$BNBR       = '004',
    [string]$KEY        = '',        # if empty, read from dll.config automatically
    [switch]$UseKey2,                # use UILogon.Key2 instead of Key1
    [string]$SsrsRoot   = '',        # auto-detected from Environment.ps1
    [switch]$Verbose
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Auto-detect server environment ────────────────────────────────────────
. (Join-Path $PSScriptRoot 'Environment.ps1')
$_prof = Get-ServerProfile
if (-not $SsrsRoot) { $SsrsRoot = $_prof.SsrsInstallRoot }
if (-not $BaseUrl)  { $BaseUrl  = $_prof.ReportServerUrl }

$uiLogonUrl = $BaseUrl.TrimEnd('/') + $LogonPath

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'UILogon.aspx Test' -ForegroundColor Cyan
Write-Host "URL  : $uiLogonUrl" -ForegroundColor Cyan
Write-Host "UID  : $UID   BNBR: $BNBR   Key: $(if ($UseKey2) { 'Key2' } else { 'Key1' })" -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ''

# ---------------------------------------------------------------------------
# Validate inputs
# ---------------------------------------------------------------------------
if ([string]::IsNullOrWhiteSpace($UID)) {
    Write-Error 'Missing -UID. Example: .\Test-UILogon.ps1 -UID testuser -PWD Test@123 -BNBR 004'
    exit 1
}
if ([string]::IsNullOrWhiteSpace($PWD)) {
    Write-Error 'Missing -PWD.'
    exit 1
}

# ---------------------------------------------------------------------------
# Read KEY from dll.config if not supplied
# ---------------------------------------------------------------------------
if ([string]::IsNullOrWhiteSpace($KEY)) {
    $keyName    = if ($UseKey2) { 'UILogon.Key2' } else { 'UILogon.Key1' }
    $dllCfgPath = Join-Path $SsrsRoot "SSRS\ReportServer\bin\BancPac.ReportingServices.BP360.dll.config"

    if (Test-Path $dllCfgPath) {
        [xml]$dllCfg   = Get-Content $dllCfgPath -Encoding UTF8
        $appSettings   = $dllCfg.SelectSingleNode('//appSettings')
        $keyNode       = $appSettings.SelectSingleNode("add[@key='$keyName']")
        if ($keyNode) {
            $KEY = $keyNode.GetAttribute('value')
            Write-Host "  Read $keyName from dll.config" -ForegroundColor Gray
        } else {
            Write-Warning "$keyName not found in dll.config. Has Configure-CustomSecurity.ps1 been run?"
            Write-Host '  Proceeding with empty KEY (expect 401)' -ForegroundColor Yellow
        }
    } else {
        Write-Warning "dll.config not found at $dllCfgPath"
        Write-Host '  Proceeding with empty KEY (expect 401)' -ForegroundColor Yellow
    }
}

# ---------------------------------------------------------------------------
# Locate curl.exe
# ---------------------------------------------------------------------------
$curlCmd = Get-Command curl.exe -ErrorAction SilentlyContinue
$curlExe = if ($curlCmd) { $curlCmd.Source } else { $null }
if (-not $curlExe) {
    # Windows 10/11 ships curl in System32
    $curlExe = "$env:SystemRoot\System32\curl.exe"
}
if (-not (Test-Path $curlExe)) {
    Write-Error 'curl.exe not found. Install curl or use Windows 10/11 which ships curl in System32.'
    exit 1
}
Write-Host "  curl : $curlExe" -ForegroundColor Gray

# ---------------------------------------------------------------------------
# Build curl arguments
# ---------------------------------------------------------------------------
$cookieFile = [System.IO.Path]::GetTempFileName()

$curlArgs = @(
    '--silent'
    '--show-error'
    '--include'                          # include response headers in output
    '--max-time', '30'
    '--cookie-jar', $cookieFile          # save cookies to file
    '--data-urlencode', "UID=$UID"
    '--data-urlencode', "PWD=$PWD"
    '--data-urlencode', "BNBR=$BNBR"
    '--data-urlencode', "KEY=$KEY"
    $uiLogonUrl
)

if ($Verbose) {
    Write-Host '  curl args:' -ForegroundColor Gray
    Write-Host "    $($curlArgs -join ' ')" -ForegroundColor Gray
    Write-Host ''
}

# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------
Write-Host 'POSTing to UILogon.aspx...' -ForegroundColor Yellow

$rawResponse = & $curlExe @curlArgs 2>&1
$curlExit    = $LASTEXITCODE

if ($curlExit -ne 0) {
    Write-Error "curl failed (exit $curlExit). Check the URL and server connectivity."
    Remove-Item $cookieFile -ErrorAction SilentlyContinue
    exit 1
}

# ---------------------------------------------------------------------------
# Parse response: split headers from body
# ---------------------------------------------------------------------------
$responseText = $rawResponse -join "`n"

# Extract HTTP status line
$statusLine = ($responseText -split "`n" | Where-Object { $_ -match '^HTTP/' } | Select-Object -First 1).Trim()
Write-Host "  $statusLine" -ForegroundColor $(if ($statusLine -match ' 2\d\d ') { 'Green' } else { 'Red' })

# Extract Set-Cookie headers
$setCookies = $rawResponse | Where-Object { $_ -match '^Set-Cookie:' }
if ($setCookies) {
    foreach ($sc in $setCookies) {
        Write-Host "  $sc" -ForegroundColor Gray
    }
}

# Extract body (everything after the blank line separator)
$bodyStart = $responseText.IndexOf("`n`n")
$body      = if ($bodyStart -ge 0) { $responseText.Substring($bodyStart + 2).Trim() } else { $responseText.Trim() }

Write-Host ''
Write-Host "  Body: $body" -ForegroundColor Gray

# ---------------------------------------------------------------------------
# Check for sqlAuthCookie — first in Set-Cookie headers, then in cookie file
# ---------------------------------------------------------------------------
Write-Host ''
$authCookieFound = $false

# Primary check: parse Set-Cookie headers from response (most reliable)
foreach ($sc in $setCookies) {
    if ($sc -match 'sqlAuthCookie=([^;]+)') {
        $cookieVal = $Matches[1]
        $preview   = if ($cookieVal.Length -gt 40) { $cookieVal.Substring(0, 40) + '...' } else { $cookieVal }
        Write-Host "  sqlAuthCookie captured ($($cookieVal.Length) chars): $preview" -ForegroundColor Green
        $authCookieFound = $true
    }
}

# Fallback check: curl cookie jar file
if (-not $authCookieFound -and (Test-Path $cookieFile)) {
    $cookieLines = Get-Content $cookieFile | Where-Object { $_ -notmatch '^#' -and $_ -match 'sqlAuthCookie' }
    if ($cookieLines) {
        $authCookieFound = $true
        foreach ($line in $cookieLines) {
            $parts = $line -split '\t'
            $cookieVal = $parts[-1]
            $preview   = if ($cookieVal.Length -gt 40) { $cookieVal.Substring(0, 40) + '...' } else { $cookieVal }
            Write-Host "  sqlAuthCookie captured (cookie jar, $($cookieVal.Length) chars): $preview" -ForegroundColor Green
        }
    }
}
Remove-Item $cookieFile -ErrorAction SilentlyContinue

# ---------------------------------------------------------------------------
# Result
# ---------------------------------------------------------------------------
Write-Host ''
Write-Host '================================================' -ForegroundColor Cyan
if ($authCookieFound) {
    Write-Host 'PASS  sqlAuthCookie returned — UILogon is working.' -ForegroundColor Green
    Write-Host ''
    Write-Host 'The WPF app can now POST these same credentials to UILogon.aspx,' -ForegroundColor White
    Write-Host 'capture sqlAuthCookie, and inject it into WebView2.' -ForegroundColor White
} else {
    Write-Host 'FAIL  sqlAuthCookie NOT found in response.' -ForegroundColor Red
    Write-Host ''
    Write-Host 'Possible causes:' -ForegroundColor Yellow
    Write-Host '  1. Wrong UID/PWD — verify with: .\Setup-Users.ps1 -CreateBankTestUsers -BankNumber 004 -Integrated' -ForegroundColor White
    Write-Host '  2. Wrong KEY — check UILogon.Key1 in dll.config matches what was configured' -ForegroundColor White
    Write-Host '  3. UILogon.aspx not deployed — re-run Deploy-CustomSecurity.ps1' -ForegroundColor White
    Write-Host '  4. SSRS not running — run: Restart-Service SQLServerReportingServices' -ForegroundColor White
    Write-Host '  5. MachineKey mismatch — check rsreportserver.config / web.config / RSPortal.exe.config' -ForegroundColor White
}
Write-Host '================================================' -ForegroundColor Cyan

exit $(if ($authCookieFound) { 0 } else { 1 })
