# Generated by Copilot under FIS AI Policy
# Build-CustomSecurity.ps1
# Builds the CustomSecurity project in the repo root.

param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Debug'
)

Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$projectPath = Join-Path $repoRoot 'CustomSecurity.csproj'

Write-Host "Building CustomSecurity extension..." -ForegroundColor Cyan
Write-Host "Configuration: $Configuration" -ForegroundColor Gray

if (-not (Test-Path $projectPath)) {
    Write-Error "Project file not found: $projectPath"
    exit 1
}
 
function Get-MsBuildPath {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
    if (-not (Test-Path $vswhere)) {
        return $null
    }

    $paths = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find 'MSBuild\**\Bin\MSBuild.exe' 2>$null
    $path = $paths | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
    return $path
}

$msbuildPath = Get-MsBuildPath

if ($msbuildPath) {
    Write-Host "Using MSBuild: $msbuildPath" -ForegroundColor Gray
    & $msbuildPath $projectPath /p:Configuration=$Configuration /p:Platform=AnyCPU /t:Rebuild
} else {
    Write-Host "MSBuild not found, using dotnet build" -ForegroundColor Yellow
    dotnet build $projectPath --configuration $Configuration
}

if ($LASTEXITCODE -ne 0) {
    Write-Host "Build failed." -ForegroundColor Red
    exit 1
}

Write-Host "Build succeeded." -ForegroundColor Green

$outputPath = Join-Path $repoRoot "bin\$Configuration\Microsoft.Samples.ReportingServices.CustomSecurity.dll"
if (Test-Path $outputPath) {
    $fileInfo = Get-Item $outputPath
    Write-Host "Output: $outputPath" -ForegroundColor Cyan
    Write-Host "  Size: $($fileInfo.Length) bytes" -ForegroundColor Gray
    Write-Host "  Modified: $($fileInfo.LastWriteTime)" -ForegroundColor Gray
} else {
    Write-Warning "Expected output not found: $outputPath"
}
