# Generated by Copilot under FIS AI Policy
# Configure-CustomSecurity.ps1
# Applies all SSRS configuration changes required for custom Forms Authentication.
# Edits rsreportserver.config, ReportServer web.config, rssrvpolicy.config,
# and the login site web.config with matching machine keys.

param(
    [string]$SSRSPath      = 'C:\Program Files\Microsoft SQL Server Reporting Services',
    [string]$LoginSitePath = 'C:\inetpub\SSRSLogin',
    [string]$LoginPort     = '8080',
    [string]$LoginHost     = 'localhost',
    [string]$ValidationKey = '',   # leave blank to auto-generate
    [string]$DecryptionKey = '',   # leave blank to auto-generate
    [switch]$StartService
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Must be Administrator
# ---------------------------------------------------------------------------
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error 'This script must be run as Administrator.'
    exit 1
}

# ---------------------------------------------------------------------------
# Helper: save an [xml] document preserving its existing encoding/declaration
# ---------------------------------------------------------------------------
function Save-Xml {
    param(
        [xml]$Doc,
        [string]$Path
    )
    $settings = [System.Xml.XmlWriterSettings]::new()
    $settings.Indent          = $true
    $settings.IndentChars     = "`t"
    $settings.Encoding        = [System.Text.Encoding]::UTF8
    $settings.OmitXmlDeclaration = $false
    $writer = [System.Xml.XmlWriter]::Create($Path, $settings)
    try { $Doc.Save($writer) } finally { $writer.Dispose() }
}

# ---------------------------------------------------------------------------
# Helper: generate a random hex string
# ---------------------------------------------------------------------------
function New-HexString {
    param([int]$ByteLength)
    $bytes = New-Object byte[] $ByteLength
    $rng   = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try   { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    ($bytes | ForEach-Object { $_.ToString('X2') }) -join ''
}

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
$rsConfig        = Join-Path $SSRSPath 'SSRS\ReportServer\rsreportserver.config'
$rsWebConfig     = Join-Path $SSRSPath 'SSRS\ReportServer\web.config'
$rsPolicyConfig  = Join-Path $SSRSPath 'SSRS\ReportServer\rssrvpolicy.config'
$portalConfig    = Join-Path $SSRSPath 'SSRS\Portal\RSPortal.exe.config'
$loginWebConfig  = Join-Path $LoginSitePath 'web.config'
$customDllPath   = Join-Path $SSRSPath 'SSRS\ReportServer\bin\Microsoft.ReportingServices.CustomSecurity.dll'

foreach ($f in @($rsConfig, $rsWebConfig, $rsPolicyConfig, $loginWebConfig)) {
    if (-not (Test-Path $f)) {
        Write-Error "Required file not found: $f"
        exit 1
    }
}

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Custom Security Configuration' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# Step 1: Machine keys
# ---------------------------------------------------------------------------
Write-Host '[1/5] Generating machine keys' -ForegroundColor Yellow

if ([string]::IsNullOrWhiteSpace($ValidationKey)) {
    $ValidationKey = New-HexString -ByteLength 64   # 128 hex chars
}
if ([string]::IsNullOrWhiteSpace($DecryptionKey)) {
    $DecryptionKey = New-HexString -ByteLength 16   # 32 hex chars
}

Write-Host "  ValidationKey : $ValidationKey" -ForegroundColor Gray
Write-Host "  DecryptionKey : $DecryptionKey" -ForegroundColor Gray

# Save keys to repo root for reference
$repoRoot  = Split-Path -Parent $PSScriptRoot
$keyFile   = Join-Path $repoRoot 'MachineKey.txt'
@"
<machineKey
  validationKey="$ValidationKey"
  decryptionKey="$DecryptionKey"
  validation="HMACSHA256"
  decryption="AES" />
"@ | Out-File -FilePath $keyFile -Encoding UTF8
Write-Host "  Keys saved to : $keyFile" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Step 2: rsreportserver.config
# ---------------------------------------------------------------------------
Write-Host '[2/5] Patching rsreportserver.config' -ForegroundColor Yellow

[xml]$rsCfg = Get-Content $rsConfig -Raw

# 2a. Replace <Authentication><AuthenticationTypes> to use <Custom />
$authNode = $rsCfg.SelectSingleNode('//Configuration/Authentication')
if ($null -eq $authNode) {
    Write-Error 'Could not find <Authentication> in rsreportserver.config'
    exit 1
}
$authTypesNode = $authNode.SelectSingleNode('AuthenticationTypes')
# Remove existing children and add <Custom />
$authTypesNode.RemoveAll()
$customEl = $rsCfg.CreateElement('Custom')
$authTypesNode.AppendChild($customEl) | Out-Null
Write-Host '  Authentication -> Custom' -ForegroundColor Green

# 2b. Replace Security extension (Windows -> Forms/CustomSecurity)
$secExt = $rsCfg.SelectNodes('//Extensions/Security/Extension') |
          Where-Object { $_.Name -eq 'Windows' }
if ($secExt) {
    $secExt.SetAttribute('Name', 'Forms')
    $secExt.SetAttribute('Type', 'Microsoft.ReportingServices.CustomSecurity.AuthenticationExtension, Microsoft.ReportingServices.CustomSecurity')
    Write-Host '  Security extension -> Forms' -ForegroundColor Green
} else {
    # Not found - add it
    $secParent = $rsCfg.SelectSingleNode('//Extensions/Security')
    if ($null -eq $secParent) {
        $secParent = $rsCfg.CreateElement('Security')
        $rsCfg.SelectSingleNode('//Extensions').AppendChild($secParent) | Out-Null
    }
    $newExt = $rsCfg.CreateElement('Extension')
    $newExt.SetAttribute('Name', 'Forms')
    $newExt.SetAttribute('Type', 'Microsoft.ReportingServices.CustomSecurity.AuthenticationExtension, Microsoft.ReportingServices.CustomSecurity')
    $secParent.AppendChild($newExt) | Out-Null
    Write-Host '  Security extension added (Forms)' -ForegroundColor Green
}

# 2c. Replace Authentication extension (Windows -> Forms/CustomSecurity)
$authExt = $rsCfg.SelectNodes('//Extensions/Authentication/Extension') |
           Where-Object { $_.Name -eq 'Windows' }
if ($authExt) {
    $authExt.SetAttribute('Name', 'Forms')
    $authExt.SetAttribute('Type', 'Microsoft.ReportingServices.CustomSecurity.AuthenticationExtension, Microsoft.ReportingServices.CustomSecurity')
    Write-Host '  Authentication extension -> Forms' -ForegroundColor Green
} else {
    $authParent = $rsCfg.SelectSingleNode('//Extensions/Authentication')
    if ($null -eq $authParent) {
        $authParent = $rsCfg.CreateElement('Authentication')
        $rsCfg.SelectSingleNode('//Extensions').AppendChild($authParent) | Out-Null
    }
    $newExt = $rsCfg.CreateElement('Extension')
    $newExt.SetAttribute('Name', 'Forms')
    $newExt.SetAttribute('Type', 'Microsoft.ReportingServices.CustomSecurity.AuthenticationExtension, Microsoft.ReportingServices.CustomSecurity')
    $authParent.AppendChild($newExt) | Out-Null
    Write-Host '  Authentication extension added (Forms)' -ForegroundColor Green
}

# 2d. Add <CustomAuthenticationUI> to <UI>
$uiNode = $rsCfg.SelectSingleNode('//Configuration/UI')
if ($null -eq $uiNode) {
    $uiNode = $rsCfg.CreateElement('UI')
    $rsCfg.SelectSingleNode('//Configuration').AppendChild($uiNode) | Out-Null
}
# Remove existing CustomAuthenticationUI if present (idempotent)
$existingCaui = $uiNode.SelectSingleNode('CustomAuthenticationUI')
if ($existingCaui) { $uiNode.RemoveChild($existingCaui) | Out-Null }

$cauiEl      = $rsCfg.CreateElement('CustomAuthenticationUI')
$loginUrlEl  = $rsCfg.CreateElement('loginUrl')
$loginUrlEl.InnerText = "http://$LoginHost:$LoginPort/Logon.aspx"
$useSslEl    = $rsCfg.CreateElement('UseSSL')
$useSslEl.InnerText   = 'false'
$cauiEl.AppendChild($loginUrlEl) | Out-Null
$cauiEl.AppendChild($useSslEl)   | Out-Null
$uiNode.PrependChild($cauiEl)    | Out-Null
Write-Host '  UI -> CustomAuthenticationUI added' -ForegroundColor Green

Save-Xml -Doc $rsCfg -Path $rsConfig
Write-Host "  Saved: $rsConfig" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Step 3: ReportServer web.config
# ---------------------------------------------------------------------------
Write-Host '[3/5] Patching ReportServer web.config' -ForegroundColor Yellow

[xml]$rwc = Get-Content $rsWebConfig -Raw
$sw       = $rwc.SelectSingleNode('//configuration/system.web')

# 3a. Authentication mode -> Forms
$authEl = $sw.SelectSingleNode('authentication')
if ($authEl) {
    $authEl.SetAttribute('mode', 'Forms')
    # Remove existing <forms> child if present
    $existingForms = $authEl.SelectSingleNode('forms')
    if ($existingForms) { $authEl.RemoveChild($existingForms) | Out-Null }
    $formsEl = $rwc.CreateElement('forms')
    $formsEl.SetAttribute('loginUrl', "http://$LoginHost:$LoginPort/Logon.aspx")
    $formsEl.SetAttribute('name',     '.ASPXFORMSAUTH')
    $formsEl.SetAttribute('timeout',  '60')
    $formsEl.SetAttribute('path',     '/')
    $authEl.AppendChild($formsEl) | Out-Null
    Write-Host '  authentication mode -> Forms' -ForegroundColor Green
}

# 3b. Identity impersonate -> false
$identEl = $sw.SelectSingleNode('identity')
if ($identEl) {
    $identEl.SetAttribute('impersonate', 'false')
    Write-Host '  identity impersonate -> false' -ForegroundColor Green
}

# 3c. Add CustomSecurity assembly to <compilation><assemblies> if not present
$assemblies = $sw.SelectSingleNode('compilation/assemblies')
if ($assemblies) {
    $existingCs = $assemblies.SelectNodes('add') | Where-Object { $_.assembly -like '*CustomSecurity*' }
    if ($existingCs) {
        # Remove existing reference with wrong PublicKeyToken
        foreach ($existing in $existingCs) {
            $assemblies.RemoveChild($existing) | Out-Null
        }
    }
    # Add correct reference with proper PublicKeyToken
    $addEl = $rwc.CreateElement('add')
    $addEl.SetAttribute('assembly', 'Microsoft.ReportingServices.CustomSecurity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=5f862221921fec1e')
    $assemblies.AppendChild($addEl) | Out-Null
    Write-Host '  CustomSecurity assembly reference added with correct PublicKeyToken' -ForegroundColor Green
}

# 3d. machineKey - remove existing, add fresh
$existingMk = $sw.SelectSingleNode('machineKey')
if ($existingMk) { $sw.RemoveChild($existingMk) | Out-Null }
$mkEl = $rwc.CreateElement('machineKey')
$mkEl.SetAttribute('validationKey', $ValidationKey)
$mkEl.SetAttribute('decryptionKey', $DecryptionKey)
$mkEl.SetAttribute('validation',    'HMACSHA256')
$mkEl.SetAttribute('decryption',    'AES')
$sw.AppendChild($mkEl) | Out-Null
Write-Host '  machineKey added to ReportServer web.config' -ForegroundColor Green

Save-Xml -Doc $rwc -Path $rsWebConfig
Write-Host "  Saved: $rsWebConfig" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Step 4: rssrvpolicy.config
# ---------------------------------------------------------------------------
Write-Host '[4/5] Patching rssrvpolicy.config' -ForegroundColor Yellow

[xml]$rsp = Get-Content $rsPolicyConfig -Raw

# Find the innermost FirstMatchCodeGroup (the ReportServer one)
$allFirstMatch = $rsp.SelectNodes("//CodeGroup[@class='FirstMatchCodeGroup']")
$targetGroup   = $allFirstMatch | Select-Object -Last 1

if ($null -eq $targetGroup) {
    Write-Warning 'Could not locate FirstMatchCodeGroup in rssrvpolicy.config - skipping policy edit.'
} else {
    # Check if already added (idempotent)
    $existing = $targetGroup.SelectSingleNode("CodeGroup[@Name='CustomSecurityCodeGroup']")
    if ($existing) {
        Write-Host '  CustomSecurityCodeGroup already present - skipped' -ForegroundColor Gray
    } else {
        $cgEl = $rsp.CreateElement('CodeGroup')
        $cgEl.SetAttribute('class',             'UnionCodeGroup')
        $cgEl.SetAttribute('version',           '1')
        $cgEl.SetAttribute('Name',              'CustomSecurityCodeGroup')
        $cgEl.SetAttribute('Description',       'Code group for the CustomSecurity extension')
        $cgEl.SetAttribute('PermissionSetName', 'FullTrust')
        $imcEl = $rsp.CreateElement('IMembershipCondition')
        $imcEl.SetAttribute('class',   'UrlMembershipCondition')
        $imcEl.SetAttribute('version', '1')
        $imcEl.SetAttribute('Url',     $customDllPath)
        $cgEl.AppendChild($imcEl) | Out-Null
        $targetGroup.AppendChild($cgEl) | Out-Null
        Write-Host '  CustomSecurityCodeGroup (FullTrust) added' -ForegroundColor Green
    }

    Save-Xml -Doc $rsp -Path $rsPolicyConfig
    Write-Host "  Saved: $rsPolicyConfig" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Step 5: Login site web.config - add matching machineKey
# ---------------------------------------------------------------------------
Write-Host '[5/6] Patching login site web.config' -ForegroundColor Yellow

[xml]$lwc  = Get-Content $loginWebConfig -Raw
$lsw       = $lwc.SelectSingleNode('//configuration/system.web')

if ($null -eq $lsw) {
    Write-Warning "No <system.web> found in $loginWebConfig - skipping machineKey injection."
} else {
    $existingLmk = $lsw.SelectSingleNode('machineKey')
    if ($existingLmk) { $lsw.RemoveChild($existingLmk) | Out-Null }
    $lmkEl = $lwc.CreateElement('machineKey')
    $lmkEl.SetAttribute('validationKey', $ValidationKey)
    $lmkEl.SetAttribute('decryptionKey', $DecryptionKey)
    $lmkEl.SetAttribute('validation',    'HMACSHA256')
    $lmkEl.SetAttribute('decryption',    'AES')
    $lsw.AppendChild($lmkEl) | Out-Null
    Write-Host '  machineKey added to login site web.config' -ForegroundColor Green

    Save-Xml -Doc $lwc -Path $loginWebConfig
    Write-Host "  Saved: $loginWebConfig" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Step 6: Portal web.config (SSRS 2016+)
# ---------------------------------------------------------------------------
Write-Host '[6/6] Patching portal config (RSPortal.exe.config)' -ForegroundColor Yellow

if (Test-Path $portalConfig) {
    [xml]$pcfg = Get-Content $portalConfig -Raw
    $pcRoot = $pcfg.SelectSingleNode('//configuration')
    $psw = $pcfg.SelectSingleNode('//configuration/system.web')
    if ($null -eq $psw) {
        $psw = $pcfg.CreateElement('system.web')
        $pcRoot.AppendChild($psw) | Out-Null
    }

    $existingPmk = $psw.SelectSingleNode('machineKey')
    if ($existingPmk) { $psw.RemoveChild($existingPmk) | Out-Null }
    $pmkEl = $pcfg.CreateElement('machineKey')
    $pmkEl.SetAttribute('validationKey', $ValidationKey)
    $pmkEl.SetAttribute('decryptionKey', $DecryptionKey)
    $pmkEl.SetAttribute('validation',    'HMACSHA256')
    $pmkEl.SetAttribute('decryption',    'AES')
    $psw.AppendChild($pmkEl) | Out-Null
    Write-Host '  machineKey added to portal config' -ForegroundColor Green

    Save-Xml -Doc $pcfg -Path $portalConfig
    Write-Host "  Saved: $portalConfig" -ForegroundColor Green
} else {
    Write-Warning "Portal config not found at: $portalConfig"
}

# ---------------------------------------------------------------------------
# Optionally start SSRS
# ---------------------------------------------------------------------------
if ($StartService) {
    Write-Host 'Starting SSRS service...' -ForegroundColor Yellow
    $svc = Get-Service -Name 'SQLServerReportingServices' -ErrorAction SilentlyContinue
    if ($svc) {
        Start-Service -Name 'SQLServerReportingServices'
        Write-Host 'SSRS service started.' -ForegroundColor Green
    } else {
        Write-Warning 'SSRS service not found. Start it manually.'
    }
}

Write-Host ''
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Configuration complete.' -ForegroundColor Cyan
Write-Host "Machine keys saved to : $keyFile" -ForegroundColor White
Write-Host "Login URL             : http://$LoginHost:$LoginPort/Logon.aspx" -ForegroundColor White
Write-Host "Reports URL           : http://$LoginHost/Reports" -ForegroundColor White
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Yellow
if (-not $StartService) {
    Write-Host '  1. Start SSRS: Start-Service SQLServerReportingServices' -ForegroundColor White
    Write-Host "  2. Test login : http://$LoginHost:$LoginPort/Logon.aspx" -ForegroundColor White
    Write-Host "  3. Open reports: http://$LoginHost/Reports" -ForegroundColor White
} else {
    Write-Host "  1. Test login : http://$LoginHost:$LoginPort/Logon.aspx" -ForegroundColor White
    Write-Host "  2. Open reports: http://$LoginHost/Reports" -ForegroundColor White
}
Write-Host '================================================' -ForegroundColor Cyan
