# Generated by Copilot under FIS AI Policy
# Deploy-Production.ps1
# Production deployment script for the SSRS Custom Security Extension.
# This script is designed to run from the extracted deployment package.
# It does NOT build — all artifacts are pre-built and included in the package.
#
# USAGE (Windows PowerShell 5.1 as Administrator):
#   .\Deploy-Production.ps1 -SqlServer "SQLHOST\INSTANCE"
#   .\Deploy-Production.ps1 -SqlServer "SQLHOST" -SqlDatabase "UserAccounts" -LoginPort 8080
#   .\Deploy-Production.ps1 -SqlServer "SQLHOST" -SqlUser "ssrs_svc" -SqlPassword "S3cur3!"
#
# PACKAGE STRUCTURE (relative to this script):
#   bin\           Pre-built DLLs and dll.config
#   web\           Logon.aspx, web.config, App_LocalResources
#   Configuration\ SSRS config templates (manual apply required)

param(
    # SQL Server connection — required
    [Parameter(Mandatory = $true)]
    [string]$SqlServer,

    [string]$SqlDatabase = 'UserAccounts',

    # SQL authentication — leave blank to use Windows Integrated Security.
    # If the SSRS service account has access to the SQL Server, Integrated Security is preferred.
    [string]$SqlUser = '',
    [string]$SqlPassword = '',

    # IIS login site
    [string]$LoginSiteName = 'SSRSLogin',
    [int]$LoginPort = 8080,

    # Where IIS will serve the login page from on the target server.
    # Default: a sibling 'SSRSLogin' folder next to this script's parent.
    [string]$LoginSitePath = '',

    # SSRS install path
    [string]$SSRSPath = 'C:\Program Files\Microsoft SQL Server Reporting Services',

    # Skip the "Type YES to continue" prompt
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$packageRoot = $PSScriptRoot
$binDir      = Join-Path $packageRoot 'bin'
$webDir      = Join-Path $packageRoot 'web'
$configDir   = Join-Path $packageRoot 'Configuration'

if ([string]::IsNullOrWhiteSpace($LoginSitePath)) {
    $LoginSitePath = Join-Path (Split-Path $packageRoot -Parent) 'SSRSLogin'
}

$dllName      = 'Microsoft.ReportingServices.CustomSecurity.dll'
$dllConfigName = "$dllName.config"
$sourceDll    = Join-Path $binDir $dllName
$sourceDllCfg = Join-Path $binDir $dllConfigName
$targetSSRSBin = Join-Path $SSRSPath 'SSRS\ReportServer\bin'

# ─────────────────────────────────────────────────────────────────────────────
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Custom Security — Production Deployment' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host "  SqlServer   : $SqlServer" -ForegroundColor Gray
Write-Host "  SqlDatabase : $SqlDatabase" -ForegroundColor Gray
Write-Host "  Auth        : $(if ($SqlUser) { "SQL auth ($SqlUser)" } else { 'Windows Integrated' })" -ForegroundColor Gray
Write-Host "  SSRS path   : $SSRSPath" -ForegroundColor Gray
Write-Host "  IIS site    : $LoginSiteName on *:${LoginPort}:" -ForegroundColor Gray
Write-Host "  Site root   : $LoginSitePath" -ForegroundColor Gray
Write-Host ''

# ── Require Administrator ──────────────────────────────────────────────────
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error 'This script must be run as Administrator.'
    exit 1
}

# ── Confirm ────────────────────────────────────────────────────────────────
if (-not $Force) {
    $confirm = Read-Host 'Deploy to production? Type YES to continue'
    if ($confirm -ne 'YES') {
        Write-Host 'Deployment cancelled.' -ForegroundColor Yellow
        exit 0
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — Validate package and prerequisites
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[1/7] Validating package and prerequisites' -ForegroundColor Yellow

if (-not (Test-Path $sourceDll)) {
    Write-Error "DLL not found in package: $sourceDll`nRe-run Package-CustomSecurity.ps1 on the build machine."
    exit 1
}
if (-not (Test-Path $sourceDllCfg)) {
    Write-Error "DLL config not found in package: $sourceDllCfg"
    exit 1
}
if (-not (Test-Path $webDir)) {
    Write-Error "web\ folder not found in package: $webDir"
    exit 1
}
if (-not (Test-Path $targetSSRSBin)) {
    Write-Error "SSRS ReportServer bin not found: $targetSSRSBin`nVerify SSRS is installed and -SSRSPath is correct."
    exit 1
}

$webCmdletsAvailable = $false
try {
    Import-Module WebAdministration -ErrorAction Stop
    $webCmdletsAvailable = [bool](Get-Command New-Website -ErrorAction SilentlyContinue)
} catch { }

if (-not $webCmdletsAvailable) {
    Write-Error 'IIS WebAdministration cmdlets not available. Run in Windows PowerShell 5.1 and install IIS Management Scripting Tools.'
    exit 1
}

Write-Host '  Package OK. IIS cmdlets available.' -ForegroundColor Green

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Build and patch connection strings
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[2/7] Patching SQL Server connection strings' -ForegroundColor Yellow

if ($SqlUser) {
    $connStr = "Server=$SqlServer; User Id=$SqlUser; Password=$SqlPassword; database=$SqlDatabase; Column Encryption Setting=Enabled"
    Write-Host "  Using SQL authentication as '$SqlUser'" -ForegroundColor Gray
} else {
    $connStr = "Server=$SqlServer; Integrated Security=SSPI; database=$SqlDatabase; Column Encryption Setting=Enabled"
    Write-Host '  Using Windows Integrated Security' -ForegroundColor Gray
}

function Set-ConnectionStringInConfig {
    param([string]$ConfigPath, [string]$ConnectionString)

    $xml = [xml](Get-Content $ConfigPath -Raw -Encoding UTF8)
    $node = $xml.SelectSingleNode(
        "//applicationSettings/Microsoft.ReportingServices.CustomSecurity.Properties.Settings/setting[@name='Database_ConnectionString']/value"
    )
    if (-not $node) {
        Write-Warning "  Database_ConnectionString node not found in: $ConfigPath — skipping patch"
        return
    }
    $node.InnerText = $ConnectionString
    $xml.Save($ConfigPath)
    Write-Host "  Patched: $(Split-Path $ConfigPath -Leaf)" -ForegroundColor Green
}

# Work on local copies in the package so originals are preserved as templates
$stagedDllCfg  = Join-Path $env:TEMP "$dllConfigName.prod"
$stagedWebCfg  = Join-Path $env:TEMP 'web.config.prod'

Copy-Item $sourceDllCfg -Destination $stagedDllCfg -Force
Copy-Item (Join-Path $webDir 'web.config') -Destination $stagedWebCfg -Force

Set-ConnectionStringInConfig -ConfigPath $stagedDllCfg -ConnectionString $connStr
Set-ConnectionStringInConfig -ConfigPath $stagedWebCfg -ConnectionString $connStr

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Backup existing SSRS configuration
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[3/7] Backing up SSRS configuration files' -ForegroundColor Yellow

$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupDir = Join-Path $SSRSPath "SSRS\ReportServer\ConfigBackup_$timestamp"
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null

$configFiles = @(
    Join-Path $SSRSPath 'SSRS\ReportServer\web.config'
    Join-Path $SSRSPath 'SSRS\ReportServer\rsreportserver.config'
    Join-Path $SSRSPath 'SSRS\ReportServer\rssrvpolicy.config'
)
foreach ($f in $configFiles) {
    if (Test-Path $f) {
        Copy-Item $f -Destination $backupDir -Force
        Write-Host "  Backed up: $(Split-Path $f -Leaf)" -ForegroundColor Gray
    }
}
Write-Host "  Backup: $backupDir" -ForegroundColor Green

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Deploy DLL and config to SSRS ReportServer\bin
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[4/7] Deploying DLL to SSRS ReportServer bin' -ForegroundColor Yellow

Copy-Item $sourceDll     -Destination $targetSSRSBin -Force
Copy-Item $stagedDllCfg  -Destination (Join-Path $targetSSRSBin $dllConfigName) -Force

# Copy all dependency DLLs too
Get-ChildItem $binDir -Filter '*.dll' -File | Where-Object { $_.Name -ne $dllName } | ForEach-Object {
    Copy-Item $_.FullName -Destination $targetSSRSBin -Force
}
Write-Host "  DLL deployed: $dllName -> $targetSSRSBin" -ForegroundColor Green

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — Deploy login site files
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[5/7] Deploying login site files' -ForegroundColor Yellow

if (-not (Test-Path $LoginSitePath)) {
    New-Item -ItemType Directory -Path $LoginSitePath -Force | Out-Null
}

# Copy all web files (Logon.aspx, App_LocalResources, etc.) except web.config (use patched version)
Get-ChildItem $webDir -Exclude 'web.config' | ForEach-Object {
    if ($_.PSIsContainer) {
        Copy-Item $_.FullName -Destination (Join-Path $LoginSitePath $_.Name) -Recurse -Force
    } else {
        Copy-Item $_.FullName -Destination $LoginSitePath -Force
    }
}
# Deploy the patched web.config
Copy-Item $stagedWebCfg -Destination (Join-Path $LoginSitePath 'web.config') -Force

# Deploy DLLs to the login site bin\ folder (ASP.NET needs them locally)
$loginBinDir = Join-Path $LoginSitePath 'bin'
if (-not (Test-Path $loginBinDir)) {
    New-Item -ItemType Directory -Path $loginBinDir -Force | Out-Null
}
Get-ChildItem $binDir -Filter '*.dll' -File | ForEach-Object {
    Copy-Item $_.FullName -Destination $loginBinDir -Force
}
Write-Host "  Login site deployed to: $LoginSitePath" -ForegroundColor Green

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — Create IIS site
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[6/7] Configuring IIS site' -ForegroundColor Yellow

$existingSite = Get-Website -Name $LoginSiteName -ErrorAction SilentlyContinue
if ($existingSite) {
    Write-Host "  Removing existing site: $LoginSiteName" -ForegroundColor Yellow
    Remove-Website -Name $LoginSiteName
}

New-Website -Name $LoginSiteName `
    -PhysicalPath $LoginSitePath `
    -Port $LoginPort `
    -ApplicationPool 'DefaultAppPool' `
    -Force | Out-Null

Write-Host "  Site created: http://<thisserver>:$LoginPort/Logon.aspx" -ForegroundColor Green

# ─────────────────────────────────────────────────────────────────────────────
# STEP 7 — Stop SSRS (config changes require restart)
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[7/7] Stopping SSRS service' -ForegroundColor Yellow
$svc = Get-Service -Name 'SQLServerReportingServices' -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq 'Running') {
    Stop-Service -Name 'SQLServerReportingServices' -Force
    Write-Host '  SSRS stopped.' -ForegroundColor Green
}

# ─────────────────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Deployment complete — MANUAL STEPS REQUIRED' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ''
Write-Host 'Before starting SSRS, complete ALL of the following:' -ForegroundColor Red
Write-Host ''
Write-Host '1. Generate machine keys (run once per environment):' -ForegroundColor White
Write-Host "   powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\Generate-MachineKeys.ps1" -ForegroundColor Gray
Write-Host ''
Write-Host '2. Apply the SAME machineKey element to:' -ForegroundColor White
Write-Host "   a. $LoginSitePath\web.config" -ForegroundColor Gray
Write-Host "   b. $SSRSPath\SSRS\ReportServer\web.config" -ForegroundColor Gray
Write-Host "   c. $SSRSPath\SSRS\ReportServer\rsreportserver.config" -ForegroundColor Gray
Write-Host ''
Write-Host '3. Apply configuration templates (use files in Configuration\):' -ForegroundColor White
Write-Host "   rsreportserver.config.template -> $SSRSPath\SSRS\ReportServer\rsreportserver.config" -ForegroundColor Gray
Write-Host "   web.config.reportserver.template -> $SSRSPath\SSRS\ReportServer\web.config" -ForegroundColor Gray
Write-Host "   rssrvpolicy.config.template -> $SSRSPath\SSRS\ReportServer\rssrvpolicy.config" -ForegroundColor Gray
Write-Host ''
Write-Host '4. Start SSRS and verify:' -ForegroundColor White
Write-Host '   Start-Service SQLServerReportingServices' -ForegroundColor Gray
Write-Host "   # Then open http://<thisserver>:$LoginPort/Logon.aspx" -ForegroundColor Gray
Write-Host ''
Write-Host "  Config backup: $backupDir" -ForegroundColor DarkGray
Write-Host '================================================' -ForegroundColor Cyan
