# Generated by Copilot under FIS AI Policy
# Deploy-CustomSecurity.ps1
# Deploys the SSRS custom security extension and login page.

param(
    [string]$SSRSPath = 'C:\Program Files\Microsoft SQL Server Reporting Services',
    [string]$LoginSiteName = 'SSRSLogin',
    [string]$LoginSitePath = 'C:\inetpub\SSRSLogin',
    [int]$LoginPort = 8080
)

Set-StrictMode -Version Latest

# Requires Administrator privileges
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error 'This script must be run as Administrator.'
    exit 1
}

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$projectPath = Join-Path $repoRoot 'CustomSecurity.csproj'
$outputDir = Join-Path $repoRoot 'bin\Release\net48'
$sourceDllCandidates = @(
    Join-Path $outputDir 'CustomSecurity.dll'
    Join-Path $outputDir 'Microsoft.ReportingServices.CustomSecurity.dll'
)
$loginRoot = $LoginSitePath
$loginBinDir = Join-Path $loginRoot 'bin'
$targetDir = Join-Path $SSRSPath 'SSRS\ReportServer\bin'

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'SSRS Custom Security Deployment' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan

# Step 1: Build
Write-Host '[1/7] Building CustomSecurity.dll' -ForegroundColor Yellow
if (-not (Test-Path $projectPath)) {
    Write-Error "Project file not found: $projectPath"
    exit 1
}

$buildScript = Join-Path $PSScriptRoot 'Build-CustomSecurity.ps1'
if (Test-Path $buildScript) {
    & $buildScript -Configuration Release
} else {
    dotnet build $projectPath --configuration Release
}

# Step 2: Stop SSRS (must happen before copying DLL to avoid 'file in use' error)
Write-Host '[2/8] Stopping SSRS service' -ForegroundColor Yellow
$serviceName = 'SQLServerReportingServices'
$service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($service -and $service.Status -eq 'Running') {
    Stop-Service -Name $serviceName -Force
    Write-Host 'SSRS service stopped' -ForegroundColor Green
} elseif (-not $service) {
    Write-Warning 'SSRS service not found. You may need to stop it manually.'
}

# Step 3: Restore Windows auth baseline so the backup captured in step 5 is always clean
Write-Host '[3/8] Restoring Windows auth baseline before backup' -ForegroundColor Yellow
$restoreScript = Join-Path $PSScriptRoot 'Restore-SSRSWindowsAuth.ps1'
if (Test-Path $restoreScript) {
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File $restoreScript `
        -SSRSPath $SSRSPath `
        -SkipServiceManagement
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Restore-SSRSWindowsAuth.ps1 failed with exit code $LASTEXITCODE"
        exit 1
    }
} else {
    Write-Warning "Restore-SSRSWindowsAuth.ps1 not found at $restoreScript - backup may not be clean"
}

# Step 4: Copy DLL
Write-Host '[4/8] Copying DLL to ReportServer bin' -ForegroundColor Yellow
$sourceDll = $sourceDllCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1

if (-not $sourceDll) {
    Write-Error "Built DLL not found. Checked: $($sourceDllCandidates -join ', ')"
    exit 1
}

if (-not (Test-Path $targetDir)) {
    Write-Error "ReportServer bin not found: $targetDir"
    exit 1
}

Copy-Item $sourceDll -Destination $targetDir -Force
Write-Host "DLL copied: $(Split-Path $sourceDll -Leaf) -> $targetDir" -ForegroundColor Green

if (-not (Test-Path $loginBinDir)) {
    New-Item -Path $loginBinDir -ItemType Directory -Force | Out-Null
}

$siteDlls = Get-ChildItem -Path $outputDir -Filter '*.dll' -File -ErrorAction SilentlyContinue
if (-not $siteDlls) {
    Write-Error "No DLL outputs found for login site deployment in: $outputDir"
    exit 1
}

foreach ($dll in $siteDlls) {
    Copy-Item -Path $dll.FullName -Destination $loginBinDir -Force
}
Write-Host "Login site assemblies copied: $($siteDlls.Count) file(s) -> $loginBinDir" -ForegroundColor Green

# Step 5: Backup configuration
Write-Host '[5/8] Backing up configuration files' -ForegroundColor Yellow
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupDir = Join-Path $SSRSPath "SSRS\ReportServer\ConfigBackup_$timestamp"
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null

$configFiles = @(
    Join-Path $SSRSPath 'SSRS\ReportServer\web.config'
    Join-Path $SSRSPath 'SSRS\ReportServer\rsreportserver.config'
    Join-Path $SSRSPath 'SSRS\ReportServer\rssrvpolicy.config'
)

foreach ($configFile in $configFiles) {
    if (Test-Path $configFile) {
        Copy-Item $configFile -Destination $backupDir -Force
        Write-Host "  Backed up: $(Split-Path $configFile -Leaf)" -ForegroundColor Gray
    }
}
Write-Host "Backup location: $backupDir" -ForegroundColor Green

# Step 6: Create IIS site
Write-Host '[6/8] Creating IIS site for Logon.aspx' -ForegroundColor Yellow

#Change by tanuj on 02 March 2016
# --- Copy login site files to $loginRoot ---
if (-not (Test-Path $loginRoot)) {
    New-Item -ItemType Directory -Path $loginRoot -Force | Out-Null
}

# Copy Logon.aspx (skip if source and destination are the same path)
$logonSource = Join-Path $repoRoot 'Logon.aspx'
$logonDest   = Join-Path $loginRoot 'Logon.aspx'
if ($logonSource -ne $logonDest) {
    Copy-Item $logonSource -Destination $loginRoot -Force
    Write-Host "  Copied Logon.aspx to $loginRoot" -ForegroundColor Green
} else {
    Write-Host "  Logon.aspx already at destination (skipped)" -ForegroundColor Yellow
}

# Copy web.config (skip if same path)
$webConfigSource = Join-Path $repoRoot 'web.config'
$webConfigDest   = Join-Path $loginRoot 'web.config'
if ($webConfigSource -ne $webConfigDest) {
    Copy-Item $webConfigSource -Destination $loginRoot -Force
    Write-Host "  Copied web.config to $loginRoot" -ForegroundColor Green
} else {
    Write-Host "  web.config already at destination (skipped)" -ForegroundColor Yellow
}

# Copy App_LocalResources (skip if same path)
$localResSource = Join-Path $repoRoot 'App_LocalResources'
$localResDest   = Join-Path $loginRoot 'App_LocalResources'
if ($localResSource -ne $localResDest) {
    if (Test-Path $localResSource) {
        Copy-Item $localResSource -Destination $loginRoot -Recurse -Force
        Write-Host "  Copied App_LocalResources\ to $loginRoot" -ForegroundColor Green
    }
} else {
    Write-Host "  App_LocalResources already at destination (skipped)" -ForegroundColor Yellow
}

# Copy DLLs to login site bin\
$loginBinDir = Join-Path $loginRoot 'bin'
if (-not (Test-Path $loginBinDir)) {
    New-Item -ItemType Directory -Path $loginBinDir -Force | Out-Null
}
$buildOutput = Join-Path $repoRoot 'bin\Release\net48'
Get-ChildItem $buildOutput -Filter '*.dll' | ForEach-Object {
    Copy-Item $_.FullName -Destination $loginBinDir -Force
    Write-Host "  Copied $($_.Name) to bin\" -ForegroundColor Gray
}
#end 

$webCmdletsAvailable = $false
try {
    Import-Module WebAdministration -ErrorAction Stop
    $webCmdletsAvailable = [bool](Get-Command New-Website -ErrorAction SilentlyContinue)
} catch {
    $webCmdletsAvailable = $false
}

if (-not $webCmdletsAvailable) {
    Write-Error @"
IIS WebAdministration cmdlets are not available.
Run this script in Windows PowerShell 5.1 (Admin) and install IIS Management Scripting Tools.
Cannot continue Step 4.
"@
    exit 1
}

$existingSite = Get-Website -Name $LoginSiteName -ErrorAction SilentlyContinue
if ($existingSite) {
    Write-Host "  Removing existing site: $LoginSiteName" -ForegroundColor Yellow
    Remove-Website -Name $LoginSiteName
}

New-Website -Name $LoginSiteName `
    -PhysicalPath $loginRoot `
    -Port $LoginPort `
    -ApplicationPool 'DefaultAppPool' `
    -Force

Write-Host "Login URL: http://localhost:$LoginPort/Logon.aspx" -ForegroundColor Cyan

# Step 7: Apply configuration (machine keys + config file edits) and start SSRS
Write-Host '[7/8] Applying SSRS configuration' -ForegroundColor Yellow
$configureScript = Join-Path $PSScriptRoot 'Configure-CustomSecurity.ps1'
if (Test-Path $configureScript) {
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File $configureScript `
        -SSRSPath      $SSRSPath `
        -LoginSitePath $LoginSitePath `
        -LoginPort     $LoginPort `
        -StartService
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Configure-CustomSecurity.ps1 failed with exit code $LASTEXITCODE"
        exit 1
    }
} else {
    Write-Warning "Configure-CustomSecurity.ps1 not found at $configureScript"
    Write-Host 'Run it manually: .\Scripts\Configure-CustomSecurity.ps1 -StartService' -ForegroundColor Yellow
}

# Step 8: Finish
Write-Host '[8/8] Deployment complete' -ForegroundColor Green
Write-Host ''
Write-Host 'NEXT:' -ForegroundColor Cyan
Write-Host "1. Test login: http://localhost:$LoginPort/Logon.aspx" -ForegroundColor White
Write-Host '2. Open reports: http://localhost/Reports' -ForegroundColor White
Write-Host ''
Write-Host "Backup location: $backupDir" -ForegroundColor Gray
Write-Host '================================================' -ForegroundColor Cyan
