# Generated by Copilot under FIS AI Policy
# Package-CustomSecurity.ps1
# Creates a self-contained deployment zip for operations/production.
# Run this on the BUILD machine after a successful build.
#
# USAGE:
#   .\Scripts\Package-CustomSecurity.ps1
#   .\Scripts\Package-CustomSecurity.ps1 -Version "1.2.3" -OutputDir "C:\Releases"
#
# OUTPUT:
#   <OutputDir>\CustomSecurity-v<Version>-<Date>.zip
#
# ZIP STRUCTURE:
#   Deploy-CustomSecurity.ps1     <- entry point
#   Configure-CustomSecurity.ps1
#   Rollback-CustomSecurity.ps1
#   Backup-Config.ps1
#   Setup-Users.ps1
#   SmokeTest-Logon.ps1
#   Test-FormsAuth.ps1
#   Test-Login.ps1
#   Test-SSRSEndpoints.ps1
#   Generate-MachineKeys.ps1
#   Set-Logging.ps1
#   bin\
#     BancPac.ReportingServices.BP360.dll
#     BancPac.ReportingServices.BP360.pdb
#   web\
#     Logon.aspx
#     App_LocalResources\
#   Setup\
#     CreateUserStore.sql
#     RestoreDatabase.sql

param(
    # Semantic version stamped onto the zip filename.
    # Defaults to the FileVersion of the built DLL.
    [string]$Version = '',

    # Where to write the zip file. Defaults to .\Deploy\ under the repo root.
    [string]$OutputDir = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot     = Split-Path -Parent $PSScriptRoot
$buildOutput  = Join-Path $repoRoot 'bin\Release'
$dllName      = 'BancPac.ReportingServices.BP360.dll'
$dllPath      = Join-Path $buildOutput $dllName

# ── Validate build output ──────────────────────────────────────────────────
if (-not (Test-Path $dllPath)) {
    Write-Error "Built DLL not found: $dllPath`nRun Build-CustomSecurity.ps1 first."
    exit 1
}

# ── Resolve version ────────────────────────────────────────────────────────
if ([string]::IsNullOrWhiteSpace($Version)) {
    $fv = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($dllPath)
    $Version = $fv.FileVersion.TrimEnd('.0').TrimEnd('.')
    if ([string]::IsNullOrWhiteSpace($Version)) { $Version = '1.0' }
}

# ── Resolve output dir ─────────────────────────────────────────────────────
if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $OutputDir = Join-Path $repoRoot 'Deploy'
}
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

$datestamp   = Get-Date -Format 'yyyyMMdd'
$zipName     = "CustomSecurity-v${Version}-${datestamp}.zip"
$zipPath     = Join-Path $OutputDir $zipName
$stagingRoot = Join-Path $env:TEMP "CustomSecurity-v$Version"

Write-Host '================================================' -ForegroundColor Cyan
Write-Host "  Packaging CustomSecurity v$Version" -ForegroundColor Cyan
Write-Host "  Output: $zipPath" -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan

# ── Clean staging area ─────────────────────────────────────────────────────
if (Test-Path $stagingRoot) { Remove-Item $stagingRoot -Recurse -Force }
New-Item -ItemType Directory -Path $stagingRoot -Force | Out-Null

# ── Helper ─────────────────────────────────────────────────────────────────
function Stage {
    param([string]$Source, [string]$RelDest)
    $dest = Join-Path $stagingRoot $RelDest
    $destDir = Split-Path $dest -Parent
    if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
    Copy-Item -Path $Source -Destination $dest -Force
    Write-Host "  + $RelDest" -ForegroundColor DarkGray
}
function StageDir {
    param([string]$SourceDir, [string]$RelDestDir)
    $dest = Join-Path $stagingRoot $RelDestDir
    Copy-Item -Path $SourceDir -Destination $dest -Recurse -Force
    Write-Host "  + $RelDestDir\" -ForegroundColor DarkGray
}

# ─────────────────────────────────────────────────────────────────────────────
# Stage: Scripts (root of zip)
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[1/4] Staging scripts' -ForegroundColor Yellow

$scripts = @(
    'Deploy-CustomSecurity.ps1'
    'Configure-CustomSecurity.ps1'
    'Rollback-CustomSecurity.ps1'
    'Backup-Config.ps1'
    'Setup-Users.ps1'
    'SmokeTest-Logon.ps1'
    'Test-FormsAuth.ps1'
    'Test-Login.ps1'
    'Test-SSRSEndpoints.ps1'
    'Generate-MachineKeys.ps1'
    'Set-Logging.ps1'
)
foreach ($s in $scripts) {
    $src = Join-Path $PSScriptRoot $s
    if (Test-Path $src) {
        Stage $src $s
    } else {
        Write-Warning "Script not found, skipping: $s"
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# Stage: Pre-built DLLs -> bin\
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[2/4] Staging pre-built DLLs' -ForegroundColor Yellow

$dlls = Get-ChildItem $buildOutput -Filter '*.dll' -File
foreach ($dll in $dlls) {
    Stage $dll.FullName "bin\$($dll.Name)"
}

# dll.config (contains connection string template — patched at deploy time)
$dllConfig = Join-Path $buildOutput "$dllName.config"
if (Test-Path $dllConfig) {
    Stage $dllConfig "bin\$dllName.config"
} else {
    Write-Warning "dll.config not found: $dllConfig"
}

# ─────────────────────────────────────────────────────────────────────────────
# Stage: ReportServer web files -> web\
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[3/4] Staging ReportServer web files' -ForegroundColor Yellow

$webFiles = @('Logon.aspx')
foreach ($wf in $webFiles) {
    $src = Join-Path $repoRoot $wf
    if (Test-Path $src) {
        Stage $src "web\$wf"
    } else {
        Write-Warning "Web file not found, skipping: $wf"
    }
}

$localResources = Join-Path $repoRoot 'App_LocalResources'
if (Test-Path $localResources) {
    StageDir $localResources 'web\App_LocalResources'
}

# ─────────────────────────────────────────────────────────────────────────────
# Stage: Setup SQL scripts -> Setup\
# ─────────────────────────────────────────────────────────────────────────────
Write-Host '[4/4] Staging setup SQL scripts' -ForegroundColor Yellow

$setupDir = Join-Path $repoRoot 'Setup'
foreach ($sql in @('CreateUserStore.sql', 'RestoreDatabase.sql')) {
    $src = Join-Path $setupDir $sql
    if (Test-Path $src) {
        Stage $src "Setup\$sql"
    } else {
        Write-Warning "SQL script not found, skipping: $sql"
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# Create zip
# ─────────────────────────────────────────────────────────────────────────────
Write-Host 'Creating zip archive...' -ForegroundColor Yellow

if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($stagingRoot, $zipPath)

# Cleanup staging
Remove-Item $stagingRoot -Recurse -Force

$zipInfo = Get-Item $zipPath
Write-Host ''
Write-Host '================================================' -ForegroundColor Green
Write-Host "  Package created successfully" -ForegroundColor Green
Write-Host "  File    : $zipPath" -ForegroundColor Green
Write-Host "  Size    : $([math]::Round($zipInfo.Length / 1MB, 2)) MB" -ForegroundColor Green
Write-Host '================================================' -ForegroundColor Green
Write-Host ''
Write-Host 'To deploy on the target server:' -ForegroundColor Cyan
Write-Host '  1. Copy the zip to the target server' -ForegroundColor White
Write-Host '  2. Extract it (e.g. to C:\Deploy\CustomSecurity)' -ForegroundColor White
Write-Host '  3. Open Windows PowerShell 5.1 as Administrator' -ForegroundColor White
Write-Host '  4. cd C:\Deploy\CustomSecurity' -ForegroundColor White
Write-Host '  5. .\Deploy-CustomSecurity.ps1 -ServiceAccount "DOMAIN\ssrssvc"' -ForegroundColor White
