# Generated by Copilot under FIS AI Policy
# Rollback-CustomSecurity.ps1
# Restores SSRS configuration to Windows Authentication.

param(
    [string]$SSRSPath = 'C:\Program Files\Microsoft SQL Server Reporting Services',
    [string]$LoginSiteName = 'SSRSLogin',
    [string]$LoginSitePath = 'C:\inetpub\SSRSLogin',
    [switch]$Force
)

Set-StrictMode -Version Latest

# Requires Administrator privileges
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error 'This script must be run as Administrator.'
    exit 1
}

$ErrorActionPreference = 'Stop'

Write-Host '================================================' -ForegroundColor Red
Write-Host 'SSRS Custom Security Rollback' -ForegroundColor Red
Write-Host '================================================' -ForegroundColor Red

if (-not $Force) {
    $confirm = Read-Host 'Type YES to continue with rollback'
    if ($confirm -ne 'YES') {
        Write-Host 'Rollback cancelled.' -ForegroundColor Yellow
        exit 0
    }
} else {
    Write-Host 'Force flag set - skipping confirmation.' -ForegroundColor Yellow
}

Write-Host '[1/6] Stopping SSRS service' -ForegroundColor Yellow
$serviceName = 'SQLServerReportingServices'
$service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($service -and $service.Status -eq 'Running') {
    Stop-Service -Name $serviceName -Force
    Write-Host 'SSRS service stopped' -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Step 2: Restore the definitive clean config files.
# The '- Copy.config' files were created immediately after the original SSRS
# install, before any Custom Security changes.  They are the ground truth.
# ---------------------------------------------------------------------------
Write-Host '[2/6] Restoring configuration files from definitive copies' -ForegroundColor Yellow
$targetDir = Join-Path $SSRSPath 'SSRS\ReportServer'

$copyMap = @(
    @{ Src = 'rsreportserver - Copy.config'; Dst = 'rsreportserver.config' }
    @{ Src = 'web - Copy.config';            Dst = 'web.config' }
    @{ Src = 'rssrvpolicy - Copy.config';    Dst = 'rssrvpolicy.config' }
)

foreach ($entry in $copyMap) {
    $src = Join-Path $targetDir $entry.Src
    $dst = Join-Path $targetDir $entry.Dst
    if (Test-Path $src) {
        Copy-Item $src -Destination $dst -Force
        Write-Host "  Restored: $($entry.Dst)" -ForegroundColor Green
    } else {
        Write-Error "Definitive copy not found: $src"
        exit 1
    }
}

Write-Host '[3/6] Removing CustomSecurity DLLs' -ForegroundColor Yellow
$dllsToRemove = @(
    Join-Path $targetDir 'bin\CustomSecurity.dll'
    Join-Path $targetDir 'bin\Microsoft.ReportingServices.CustomSecurity.dll'
)
foreach ($dllPath in $dllsToRemove) {
    if (Test-Path $dllPath) {
        Remove-Item $dllPath -Force
        Write-Host "  Removed: $(Split-Path $dllPath -Leaf)" -ForegroundColor Green
    }
}

Write-Host '[4/6] Removing IIS login site' -ForegroundColor Yellow
Import-Module WebAdministration -ErrorAction SilentlyContinue
$loginSite = Get-Website -Name $LoginSiteName -ErrorAction SilentlyContinue
if ($loginSite) {
    Remove-Website -Name $LoginSiteName -ErrorAction SilentlyContinue
    Write-Host "Removed IIS site: $LoginSiteName" -ForegroundColor Green
} else {
    Write-Host 'Login site not found' -ForegroundColor Gray
}

Write-Host '[5/6] Removing login site folder' -ForegroundColor Yellow
if (-not [string]::IsNullOrWhiteSpace($LoginSitePath) -and (Test-Path $LoginSitePath)) {
    Remove-Item -Path $LoginSitePath -Recurse -Force
    Write-Host "Removed login site folder: $LoginSitePath" -ForegroundColor Green
} else {
    Write-Host "Login site folder not found or not specified: $LoginSitePath" -ForegroundColor Gray
}

Write-Host '[6/6] Starting SSRS service' -ForegroundColor Yellow
if ($service) {
    Start-Service -Name $serviceName
    Write-Host 'SSRS service started' -ForegroundColor Green
}

Write-Host ''
Write-Host 'Rollback complete.' -ForegroundColor Green
Write-Host 'SSRS restored to Windows Authentication from definitive copy files.' -ForegroundColor White
