# Generated by Copilot under FIS AI Policy
# Collect-IIS500Diagnostics.ps1
# Captures basic diagnostics for SSRS 500 errors on Reports/ReportServer.

param(
    [string]$ServerUrl = 'http://vwmazbp360test',
    [string]$OutputDir = '.\\Diagnostics',
    [switch]$IncludeEventLogs
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$fullOutputDir = Join-Path $PSScriptRoot $OutputDir
if (-not (Test-Path $fullOutputDir)) {
    New-Item -Path $fullOutputDir -ItemType Directory -Force | Out-Null
}

function Save-TextFile {
    param(
        [string]$Path,
        [string]$Content
    )
    $Content | Out-File -FilePath $Path -Encoding UTF8
}

function Invoke-Capture {
    param(
        [string]$Url,
        [string]$Name
    )

    $safeName = $Name -replace '[^A-Za-z0-9\-_]', '_'
    $basePath = Join-Path $fullOutputDir ("${timestamp}_${safeName}")

    try {
        $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 20 -MaximumRedirection 0
        $statusCode = [int]$response.StatusCode
        $headers = $response.Headers | Out-String
        Save-TextFile -Path ("${basePath}_headers.txt") -Content $headers
        Save-TextFile -Path ("${basePath}_body.txt") -Content $response.Content
        Write-Host ("{0}: {1}" -f $Name, $statusCode) -ForegroundColor Green
    }
    catch {
        $statusCode = 0
        $headers = ''
        $body = ''
        $ex = $_.Exception
        if ($null -ne $ex -and $ex.PSObject.Properties.Match('Response').Count -gt 0) {
            $resp = $ex.Response
            if ($null -ne $resp) {
                try { $statusCode = [int]$resp.StatusCode } catch {}
                try { $headers = $resp.Headers | Out-String } catch {}
            }
        }
        try { $body = $ex.Message } catch {}
        Save-TextFile -Path ("${basePath}_headers.txt") -Content $headers
        Save-TextFile -Path ("${basePath}_body.txt") -Content $body
        Write-Host ("{0}: {1}" -f $Name, $statusCode) -ForegroundColor Red
    }
}

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Collect IIS/SSRS 500 Diagnostics' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
Write-Host ("Output: {0}" -f $fullOutputDir) -ForegroundColor Gray

$reportsUrl = "$ServerUrl/Reports"
$reportServerUrl = "$ServerUrl/ReportServer"

Invoke-Capture -Url $reportsUrl -Name 'Reports'
Invoke-Capture -Url $reportServerUrl -Name 'ReportServer'

# SSRS service status
$service = Get-Service -Name SQLServerReportingServices -ErrorAction SilentlyContinue
if ($service) {
    Save-TextFile -Path (Join-Path $fullOutputDir ("${timestamp}_ssrs_service.txt")) -Content ("{0}: {1}" -f $service.DisplayName, $service.Status)
}

# IIS app pool info (best effort)
try {
    Import-Module WebAdministration -ErrorAction Stop
    $pool = Get-Item IIS:\AppPools\DefaultAppPool -ErrorAction SilentlyContinue
    if ($pool) {
        Save-TextFile -Path (Join-Path $fullOutputDir ("${timestamp}_iis_apppool.txt")) -Content ($pool | Format-List * | Out-String)
    }
}
catch {
    Save-TextFile -Path (Join-Path $fullOutputDir ("${timestamp}_iis_apppool.txt")) -Content ('WebAdministration module not available: ' + $_.Exception.Message)
}

# Optional event logs (last 50 Application entries)
if ($IncludeEventLogs) {
    try {
        $events = Get-WinEvent -FilterHashtable @{ LogName = 'Application' } -MaxEvents 50 | Select-Object TimeCreated, ProviderName, Id, LevelDisplayName, Message
        Save-TextFile -Path (Join-Path $fullOutputDir ("${timestamp}_application_events.txt")) -Content ($events | Format-List * | Out-String)
    }
    catch {
        Save-TextFile -Path (Join-Path $fullOutputDir ("${timestamp}_application_events.txt")) -Content ('Failed to read event logs: ' + $_.Exception.Message)
    }
}

Write-Host '================================================' -ForegroundColor Cyan
Write-Host 'Diagnostics complete.' -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan
