# Generated by Copilot under FIS AI Policy
# Generate-MachineKeys.ps1
# Creates machine keys for Forms Authentication.

Set-StrictMode -Version Latest

function New-HexString {
    param(
        [int]$ByteLength
    )

    $bytes = New-Object byte[] $ByteLength
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }

    ($bytes | ForEach-Object { $_.ToString('X2') }) -join ''
}

$validationKey = New-HexString -ByteLength 64  # 128 hex chars
$decryptionKey = New-HexString -ByteLength 16  # 32 hex chars

$machineKeyXml = @"
<machineKey
  validationKey="$validationKey"
  decryptionKey="$decryptionKey"
  validation="HMACSHA256"
  decryption="AES" />
"@

Write-Host '================================================' -ForegroundColor Green
Write-Host 'Machine key generated' -ForegroundColor Green
Write-Host '================================================' -ForegroundColor Green
Write-Host ''
Write-Host $machineKeyXml -ForegroundColor Yellow
Write-Host ''
Write-Host 'Apply this exact machineKey to all three configs:' -ForegroundColor Cyan
Write-Host '1. Login page web.config (repo root)' -ForegroundColor White
Write-Host '2. ReportServer web.config' -ForegroundColor White
Write-Host '3. rsreportserver.config' -ForegroundColor White
Write-Host ''
Write-Host 'The values must be identical in all three files.' -ForegroundColor Red
Write-Host '================================================' -ForegroundColor Green

$repoRoot = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $repoRoot 'MachineKey.txt'
$machineKeyXml | Out-File -FilePath $outFile -Encoding UTF8
Write-Host "Machine key saved to: $outFile" -ForegroundColor Green
