# Generated by Copilot under FIS AI Policy
# Set-Logging.ps1
# Enables or disables verbose logging for the SSRSLogin site.
# Controls three independent logging layers:
#   1. Serilog     - application-level logging (LoggingHelper.cs)
#   2. ASP.NET     - compilation debug flag (detailed stack traces)
#   3. IIS FREB    - Failed Request Tracing (pipeline-level 4xx/5xx capture)
#
# Usage:
#   .\Scripts\Set-Logging.ps1 -Level Verbose      # Full verbose + FREB on
#   .\Scripts\Set-Logging.ps1 -Level Debug         # Debug + FREB on
#   .\Scripts\Set-Logging.ps1 -Level Information   # Normal production level
#   .\Scripts\Set-Logging.ps1 -Level Off           # Silent (Fatal only)
#   .\Scripts\Set-Logging.ps1 -Status              # Show current settings

param(
    [ValidateSet('Verbose', 'Debug', 'Information', 'Warning', 'Error', 'Off')]
    [string]$Level = 'Debug',
    [string]$LoginSiteName = 'SSRSLogin',
    [string]$LoginSitePath = 'C:\inetpub\SSRSLogin',
    [switch]$Status
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Must be Administrator
# ---------------------------------------------------------------------------
$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error 'This script must be run as Administrator.'
    exit 1
}

if (-not $Level -and -not $Status) {
    Write-Host ''
    Write-Host 'Usage:' -ForegroundColor Cyan
    Write-Host '  .\Scripts\Set-Logging.ps1 -Level Verbose      # Full verbose + FREB on' -ForegroundColor White
    Write-Host '  .\Scripts\Set-Logging.ps1 -Level Debug         # Debug + FREB on' -ForegroundColor White
    Write-Host '  .\Scripts\Set-Logging.ps1 -Level Information   # Normal production level' -ForegroundColor White
    Write-Host '  .\Scripts\Set-Logging.ps1 -Level Warning       # Warnings and errors only' -ForegroundColor White
    Write-Host '  .\Scripts\Set-Logging.ps1 -Level Off           # Silent (Fatal only)' -ForegroundColor White
    Write-Host '  .\Scripts\Set-Logging.ps1 -Status              # Show current settings' -ForegroundColor White
    Write-Host ''
    exit 0
}

# ---------------------------------------------------------------------------
# Serilog keys managed in web.config appSettings
# ---------------------------------------------------------------------------
$serilogKeys = @(
    'MinimumLogLevel'
    'LogLevel_Authorization'
    'LogLevel_Logon'
    'LogLevel_AuthenticationExtension'
    'LogLevel_AuthenticationUtilities'
)

# ---------------------------------------------------------------------------
# Helper: save [xml] doc with UTF-8 + indentation
# ---------------------------------------------------------------------------
function Save-Xml {
    param(
        [xml]$Doc,
        [string]$Path
    )
    $settings = [System.Xml.XmlWriterSettings]::new()
    $settings.Indent             = $true
    $settings.IndentChars        = "`t"
    $settings.Encoding           = [System.Text.Encoding]::UTF8
    $settings.OmitXmlDeclaration = $false
    $writer = [System.Xml.XmlWriter]::Create($Path, $settings)
    try { $Doc.Save($writer) } finally { $writer.Dispose() }
}

# ---------------------------------------------------------------------------
# Helper: read current settings from web.config
# ---------------------------------------------------------------------------
function Get-LoggingStatus {
    param([string]$WebConfigPath)

    $result = [ordered]@{}

    if (-not (Test-Path $WebConfigPath)) {
        Write-Warning "web.config not found: $WebConfigPath"
        return $result
    }

    [xml]$cfg = [System.IO.File]::ReadAllText($WebConfigPath)

    foreach ($key in $serilogKeys) {
        $node = $cfg.SelectSingleNode("/configuration/appSettings/add[@key='$key']")
        $result[$key] = if ($node) { $node.GetAttribute('value') } else { '(not set)' }
    }

    $compileNode = $cfg.SelectSingleNode('/configuration/system.web/compilation')
    $result['compilation_debug'] = if ($compileNode) { $compileNode.GetAttribute('debug') } else { '(not set)' }

    return $result
}

# ---------------------------------------------------------------------------
# Helper: check IIS FREB state
# ---------------------------------------------------------------------------
function Get-FREBStatus {
    param([string]$SiteName)
    try {
        Import-Module WebAdministration -ErrorAction Stop
        $filter = "system.applicationHost/sites/site[@name='$SiteName']/traceFailedRequestsLogging"
        $node = Get-WebConfigurationProperty -pspath 'IIS:\' -filter $filter -name 'enabled' -ErrorAction SilentlyContinue
        if ($null -ne $node) { return [bool]$node.Value } else { return $false }
    } catch {
        return $null  # WebAdministration unavailable
    }
}

# ---------------------------------------------------------------------------
# -Status: display current settings and exit
# ---------------------------------------------------------------------------
if ($Status) {
    $webConfigPath = Join-Path $LoginSitePath 'web.config'
    Write-Host ''
    Write-Host '================================================' -ForegroundColor Cyan
    Write-Host "Logging status for: $LoginSiteName" -ForegroundColor Cyan
    Write-Host '================================================' -ForegroundColor Cyan

    Write-Host ''
    Write-Host '--- Serilog / ASP.NET (web.config) ---' -ForegroundColor Yellow
    $current = Get-LoggingStatus -WebConfigPath $webConfigPath
    foreach ($entry in $current.GetEnumerator()) {
        $color = 'White'
        if ($entry.Value -in @('Verbose', 'Debug')) { $color = 'Cyan' }
        elseif ($entry.Value -in @('Warning', 'Error', 'Fatal')) { $color = 'DarkYellow' }
        Write-Host ("  {0,-45} {1}" -f $entry.Key, $entry.Value) -ForegroundColor $color
    }

    Write-Host ''
    Write-Host '--- IIS Failed Request Tracing (FREB) ---' -ForegroundColor Yellow
    $frebState = Get-FREBStatus -SiteName $LoginSiteName
    if ($null -eq $frebState) {
        Write-Host '  (WebAdministration module unavailable - run in Windows PowerShell 5.1 Admin)' -ForegroundColor DarkYellow
    } elseif ($frebState) {
        Write-Host '  FREB: Enabled' -ForegroundColor Cyan
    } else {
        Write-Host '  FREB: Disabled' -ForegroundColor Gray
    }

    Write-Host ''
    Write-Host "Log files : C:\Logs\SSRS\CustomSecurity\" -ForegroundColor Gray
    Write-Host "FREB files: C:\inetpub\logs\FailedReqLogFiles\W3SVC*\" -ForegroundColor Gray
    Write-Host '================================================' -ForegroundColor Cyan
    exit 0
}

# ---------------------------------------------------------------------------
# Map -Level to concrete settings
# ---------------------------------------------------------------------------
# 'Off' maps to Serilog 'Fatal' (nothing below Fatal is emitted)
$serilogLevel = if ($Level -eq 'Off') { 'Fatal' } else { $Level }

# Enable ASP.NET debug and FREB for Verbose or Debug levels
$enableDebug = ($Level -in @('Verbose', 'Debug'))
$enableFREB  = ($Level -in @('Verbose', 'Debug'))

# ---------------------------------------------------------------------------
# Apply changes
# ---------------------------------------------------------------------------
$webConfigPath = Join-Path $LoginSitePath 'web.config'

if (-not (Test-Path $webConfigPath)) {
    Write-Error "web.config not found: $webConfigPath"
    exit 1
}

Write-Host ''
Write-Host '================================================' -ForegroundColor Cyan
Write-Host "Setting logging level: $Level" -ForegroundColor Cyan
Write-Host '================================================' -ForegroundColor Cyan

# --- 1. Serilog keys + compilation debug in web.config ---
Write-Host '[1/3] Updating web.config (Serilog + ASP.NET debug)' -ForegroundColor Yellow

[xml]$cfg = [System.IO.File]::ReadAllText($webConfigPath)

# Serilog appSettings keys
$appSettings = $cfg.SelectSingleNode('/configuration/appSettings')
if (-not $appSettings) {
    $appSettings = $cfg.CreateElement('appSettings')
    $cfg.SelectSingleNode('/configuration').AppendChild($appSettings) | Out-Null
}

foreach ($key in $serilogKeys) {
    $node = $appSettings.SelectSingleNode("add[@key='$key']")
    if ($node) {
        $node.SetAttribute('value', $serilogLevel)
    } else {
        $add = $cfg.CreateElement('add')
        $add.SetAttribute('key', $key)
        $add.SetAttribute('value', $serilogLevel)
        $appSettings.AppendChild($add) | Out-Null
    }
    Write-Host "  $key = $serilogLevel" -ForegroundColor Gray
}

# ASP.NET compilation debug
$compileNode = $cfg.SelectSingleNode('/configuration/system.web/compilation')
if ($compileNode) {
    $compileNode.SetAttribute('debug', ($enableDebug.ToString().ToLower()))
    Write-Host "  compilation debug = $($enableDebug.ToString().ToLower())" -ForegroundColor Gray
}

Save-Xml -Doc $cfg -Path $webConfigPath
Write-Host '  Saved web.config' -ForegroundColor Green

# --- 2. IIS FREB ---
Write-Host '[2/3] Configuring IIS Failed Request Tracing (FREB)' -ForegroundColor Yellow

$frebDone = $false
try {
    Import-Module WebAdministration -ErrorAction Stop

    $siteFilter = "system.applicationHost/sites/site[@name='$LoginSiteName']/traceFailedRequestsLogging"

    if ($enableFREB) {
        # Enable FREB at the site level
        Set-WebConfigurationProperty -pspath 'IIS:\' `
            -filter $siteFilter -name 'enabled' -value $true
        Set-WebConfigurationProperty -pspath 'IIS:\' `
            -filter $siteFilter -name 'maxLogFiles' -value 50

        # Add trace rule for all paths, 400-599, Verbose
        $tracePath = "IIS:\Sites\$LoginSiteName"
        $ruleFilter = 'system.webServer/tracing/traceFailedRequests'

        # Remove existing rule for '*' if present to avoid duplicates
        $existing = Get-WebConfigurationProperty -pspath $tracePath `
            -filter "$ruleFilter/add[@path='*']" -name 'path' -ErrorAction SilentlyContinue
        if ($existing) {
            Clear-WebConfiguration -pspath $tracePath -filter "$ruleFilter"
        }

        Add-WebConfigurationProperty -pspath $tracePath `
            -filter $ruleFilter -name '.' `
            -value @{ path = '*' }

        Add-WebConfigurationProperty -pspath $tracePath `
            -filter "$ruleFilter/add[@path='*']/traceAreas" -name '.' `
            -value @{ provider = 'ASP'; verbosity = 'Verbose' }

        Add-WebConfigurationProperty -pspath $tracePath `
            -filter "$ruleFilter/add[@path='*']/traceAreas" -name '.' `
            -value @{ provider = 'ASPNET'; areas = 'Infrastructure,Module,Page,AppServices'; verbosity = 'Verbose' }

        Set-WebConfigurationProperty -pspath $tracePath `
            -filter "$ruleFilter/add[@path='*']/failureDefinitions" `
            -name 'statusCodes' -value '400-599'

        Write-Host '  FREB enabled (400-599, Verbose, max 50 files)' -ForegroundColor Green

    } else {
        # Disable FREB
        Set-WebConfigurationProperty -pspath 'IIS:\' `
            -filter $siteFilter -name 'enabled' -value $false

        # Remove any trace rules
        $tracePath = "IIS:\Sites\$LoginSiteName"
        Clear-WebConfiguration -pspath $tracePath `
            -filter 'system.webServer/tracing/traceFailedRequests' -ErrorAction SilentlyContinue

        Write-Host '  FREB disabled' -ForegroundColor Green
    }
    $frebDone = $true

} catch {
    Write-Warning "IIS WebAdministration unavailable: $_"
    Write-Warning 'FREB not changed. Run this script in Windows PowerShell 5.1 (Admin) for FREB support.'
}

# --- 3. Summary ---
Write-Host '[3/3] Done' -ForegroundColor Yellow
Write-Host ''
Write-Host '================================================' -ForegroundColor Cyan
Write-Host "Logging level applied : $Level" -ForegroundColor White
Write-Host "Serilog level         : $serilogLevel" -ForegroundColor White
Write-Host "ASP.NET debug         : $($enableDebug.ToString().ToLower())" -ForegroundColor White
if ($frebDone) {
    Write-Host "FREB                  : $(if ($enableFREB) { 'enabled' } else { 'disabled' })" -ForegroundColor White
} else {
    Write-Host "FREB                  : not changed (requires WebAdministration)" -ForegroundColor DarkYellow
}
Write-Host ''
Write-Host "Log files  : C:\Logs\SSRS\CustomSecurity\" -ForegroundColor Gray
if ($enableFREB -and $frebDone) {
    Write-Host "FREB files : C:\inetpub\logs\FailedReqLogFiles\W3SVC*\" -ForegroundColor Gray
}
Write-Host ''
Write-Host 'web.config reloads automatically - no app pool recycle needed.' -ForegroundColor DarkGray
Write-Host '================================================' -ForegroundColor Cyan
